-- ----- RMA Lua Contract ----- --
-- deps: local addon = select(2, ...)
-- shared: direct addon namespace bindings
-- exports: publish module APIs on addon.*
-- events: none

local addon = select(2, ...)

addon.Diagnose = addon.Diagnose or {}
addon.Diag = addon.Diag or addon.Diagnose

local Diag = addon.Diag

Diag.I = Diag.I or {}
Diag.W = Diag.W or {}
Diag.E = Diag.E or {}
Diag.D = Diag.D or {}
Diag.A = Diag.A or {}

-- ==================== Assertion Messages ==================== --
-- Bootstrap --
Diag.A.BootstrapEnsureNamespaceRequiresARootTable = "ensureNamespace requires a root table"
Diag.A.BootstrapEnsureNamespaceRequiresNonEmptyStringKeys = "ensureNamespace requires non-empty string keys"
Diag.A.BootstrapInternalEventsNotInitialized = "RMA internal events are not initialized"
Diag.A.BootstrapLootChatHandlerNotInitialized = "RMA Loot chat handler is not initialized"
Diag.A.BootstrapMissingService = "RMA missing service: %s"
Diag.A.BootstrapMissingServiceMethod = "RMA missing service method: %s.%s"
Diag.A.BootstrapPartyLeaderIndexApiNotInitialized = "RMA party leader index API is not initialized"
Diag.A.BootstrapPartyMemberCountApiNotInitialized = "RMA party member count API is not initialized"
Diag.A.BootstrapRaidMemberCountApiNotInitialized = "RMA raid member count API is not initialized"
Diag.A.BootstrapRaidRosterApiNotInitialized = "RMA raid roster API is not initialized"
Diag.A.BootstrapRealmNameApiNotInitialized = "RMA realm name API is not initialized"
Diag.A.BootstrapTimeApiNotInitialized = "RMA time API is not initialized"
Diag.A.BootstrapUnitNameApiNotInitialized = "RMA unit name API is not initialized"

-- Database --
Diag.A.CommsDependencyNotInitialized = "Comms dependency is not initialized"
Diag.A.CommsPayloadHelpersNotInitialized = "Comms payload helpers are not initialized"
Diag.A.DatabaseBootstrapMissingAddonDb = "RMA DB bootstrap missing addon.DB"
Diag.A.DatabaseOwnerNotInitialized = "RMA %s is not initialized"
Diag.A.ItemDependencyNotInitialized = "Item dependency is not initialized"
Diag.A.LibDeflateNotInitialized = "LibDeflate is not initialized"
Diag.A.LoggerRaidOfferEventNotInitialized = "Logger raid-offer event is not initialized"
Diag.A.LoggerRaidSelectionEventNotInitialized = "Logger raid selection event is not initialized"
Diag.A.LootMethodChangeEventNotInitialized = "Loot-method-change event is not initialized"
Diag.A.OptionsEventBusSenderNotInitialized = "Options event bus sender is not initialized"
Diag.A.OptionsLoadedEventNotInitialized = "Options-loaded event is not initialized"
Diag.A.RaidCreateEventNotInitialized = "Raid-create event is not initialized"
Diag.A.RaidEventCodecDependencyNotInitialized = "Raid event codec dependency is not initialized"
Diag.A.RaidEventReducerNotInitialized = "Raid event reducer is not initialized"
Diag.A.RaidInstanceEventNotInitialized = "Raid instance event is not initialized"
Diag.A.RaidQueriesTimeProviderNotInitialized = "Raid queries time provider is not initialized"
Diag.A.RaidReplicationCommitEventNotInitialized = "Raid replication commit event is not initialized"
Diag.A.RaidRosterEventNotInitialized = "Raid-roster event is not initialized"
Diag.A.RaidServiceDependencyNotInitialized = "Raid service dependency is not initialized"
Diag.A.RaidStartTimestampNotInitialized = "Raid start timestamp is not initialized"
Diag.A.RaidStoreDependencyNotInitialized = "Raid store dependency is not initialized"
Diag.A.RaidStoreMonotonicTimeApiNotInitialized = "Raid store monotonic time API is not initialized"
Diag.A.RaidStoreTimeProviderNotInitialized = "Raid store time provider is not initialized"
Diag.A.RecoveredRaidSelectionFailed = "Recovered raid selection failed"
Diag.A.SavedVariablesRaidStoreResolverNotInitialized = "SavedVariables raid store resolver is not initialized"
Diag.A.SavedVariablesReservesSaveHandlerNotInitialized = "SavedVariables reserves save handler is not initialized"
Diag.A.SavedVariablesReservesServiceNotInitialized = "SavedVariables reserves service is not initialized"
Diag.A.SyncClockApiNotInitialized = "Sync clock API is not initialized"
Diag.A.SyncEventBusNotInitialized = "Sync event bus is not initialized"
Diag.A.SyncEventPublisherNotInitialized = "Sync event publisher is not initialized"
Diag.A.SyncInternalEventsNotInitialized = "Sync internal events are not initialized"
Diag.A.SyncPlayerIdentityApiNotInitialized = "Sync player identity API is not initialized"
Diag.A.SyncProtocolDependencyNotInitialized = "Sync protocol dependency is not initialized"
Diag.A.SyncProtocolMustBeVersion5 = "Sync protocol must be version 5"
Diag.A.SyncSessionClockNotInitialized = "Sync session clock is not initialized"
Diag.A.SyncSessionDependencyNotInitialized = "Sync session dependency is not initialized"
Diag.A.SyncSessionPlayerIdentityNotInitialized = "Sync session player identity is not initialized"
Diag.A.SyncTimerDependencyNotInitialized = "Sync timer dependency is not initialized"
Diag.A.SyncWoWEventsNotInitialized = "Sync WoW events are not initialized"
Diag.A.TimerDependencyNotInitialized = "Timer dependency is not initialized"
Diag.A.ZoneChangeEventNotInitialized = "Zone-change event is not initialized"

-- Modules --
Diag.A.AttendanceActionsChangedEventNotInitialized = "Attendance actions changed event is not initialized"
Diag.A.AttendanceActionsEventPublisherNotInitialized = "Attendance actions event publisher is not initialized"
Diag.A.AttendanceActionsInternalEventsNotInitialized = "Attendance actions internal events are not initialized"
Diag.A.AttendanceCsvRowEncoderNotInitialized = "Attendance CSV row encoder is not initialized"
Diag.A.AttendanceExportRaidProjectionsNotInitialized = "Attendance export raid projections are not initialized"
Diag.A.ChatGroupHelperOwnerNotInitialized = "Chat group helper owner is not initialized"
Diag.A.ChatGroupPolicyHelperNotInitialized = "Chat group policy helper is not initialized"
Diag.A.ChatThrottleLibNotInitialized = "ChatThrottleLib is not initialized"
Diag.A.CommsAddonMetadataApiNotInitialized = "Comms addon metadata API is not initialized"
Diag.A.CommsInstanceStateApiNotInitialized = "Comms instance state API is not initialized"
Diag.A.CommsPartyMemberCountApiNotInitialized = "Comms party member count API is not initialized"
Diag.A.CommsRaidMemberCountApiNotInitialized = "Comms raid member count API is not initialized"
Diag.A.CommsSenderNameNormalizerNotInitialized = "Comms sender name normalizer is not initialized"
Diag.A.CommsUnitNameApiNotInitialized = "Comms unit name API is not initialized"
Diag.A.ConfigControllerNotInitialized = "Config controller is not initialized"
Diag.A.DebugEntrypointNotInitialized = "Debug entrypoint is not initialized"
Diag.A.EffectsFrameScriptBinderNotInitialized = "Effects frame script binder is not initialized"
Diag.A.EquipInspectCompletedEventNotInitialized = "EquipInspect completed event is not initialized"
Diag.A.EquipInspectCoordinatorNotInitialized = "EquipInspect coordinator is not initialized"
Diag.A.EquipInspectEventBusListenerNotInitialized = "EquipInspect event bus listener is not initialized"
Diag.A.EquipInspectEventPublisherNotInitialized = "EquipInspect event publisher is not initialized"
Diag.A.EquipInspectForwardedEventResolverNotInitialized = "EquipInspect forwarded-event resolver is not initialized"
Diag.A.EquipInspectInspectCapabilityApiNotInitialized = "EquipInspect inspect capability API is not initialized"
Diag.A.EquipInspectInternalEventsNotInitialized = "EquipInspect internal events are not initialized"
Diag.A.EquipInspectInventoryItemLinkApiNotInitialized = "EquipInspect inventory item link API is not initialized"
Diag.A.EquipInspectInventoryItemQualityApiNotInitialized = "EquipInspect inventory item quality API is not initialized"
Diag.A.EquipInspectInventoryItemTextureApiNotInitialized = "EquipInspect inventory item texture API is not initialized"
Diag.A.EquipInspectItemInfoApiNotInitialized = "EquipInspect item info API is not initialized"
Diag.A.EquipInspectItemInfoEventNotInitialized = "EquipInspect item-info event is not initialized"
Diag.A.EquipInspectNotifyInspectApiNotInitialized = "EquipInspect notify inspect API is not initialized"
Diag.A.EquipInspectRaidCreateEventNotInitialized = "EquipInspect raid-create event is not initialized"
Diag.A.EquipInspectStartedEventNotInitialized = "EquipInspect started event is not initialized"
Diag.A.EquipInspectTalentReadyEventNotInitialized = "EquipInspect talent-ready event is not initialized"
Diag.A.EquipInspectTimeApiNotInitialized = "EquipInspect time API is not initialized"
Diag.A.EquipInspectUnitConnectionApiNotInitialized = "EquipInspect unit connection API is not initialized"
Diag.A.EquipInspectUnitExistenceApiNotInitialized = "EquipInspect unit existence API is not initialized"
Diag.A.EquipInspectUnitGuidApiNotInitialized = "EquipInspect unit GUID API is not initialized"
Diag.A.EquipInspectUnitRangeApiNotInitialized = "EquipInspect unit range API is not initialized"
Diag.A.EquipInspectUpdateEventNotInitialized = "EquipInspect update event is not initialized"
Diag.A.IgnoredMobsActivationSnapshotRequired = "IgnoredMobs activation snapshot is required"
Diag.A.InspectCoordinatorClearApiNotInitialized = "InspectCoordinator clear API is not initialized"
Diag.A.InspectCoordinatorCombatApiNotInitialized = "InspectCoordinator combat API is not initialized"
Diag.A.InspectCoordinatorEventListenerNotInitialized = "InspectCoordinator event listener is not initialized"
Diag.A.InspectCoordinatorEventResolverNotInitialized = "InspectCoordinator event resolver is not initialized"
Diag.A.InspectCoordinatorRegenEventMissing = "InspectCoordinator regen event missing"
Diag.A.InspectCoordinatorTimeApiNotInitialized = "InspectCoordinator time API is not initialized"
Diag.A.ItemCacheItemInfoApiNotInitialized = "Item cache item info API is not initialized"
Diag.A.ItemCacheTimeApiNotInitialized = "Item cache time API is not initialized"
Diag.A.LibSerializeNotInitialized = "LibSerialize is not initialized"
Diag.A.ListControllerFrameCreationApiNotInitialized = "List controller frame creation API is not initialized"
Diag.A.LoggerActionsDataChangedEventNotInitialized = "Logger actions data-changed event is not initialized"
Diag.A.LoggerActionsEventPublisherNotInitialized = "Logger actions event publisher is not initialized"
Diag.A.LoggerActionsInternalEventsNotInitialized = "Logger actions internal events are not initialized"
Diag.A.LoggerActionsLootChangedEventNotInitialized = "Logger actions loot-changed event is not initialized"
Diag.A.LoggerActionsTimeProviderNotInitialized = "Logger actions time provider is not initialized"
Diag.A.LoggerCsvRowEncoderNotInitialized = "Logger CSV row encoder is not initialized"
Diag.A.LoggerExportHelpersNotInitialized = "Logger export helpers are not initialized"
Diag.A.LoggerExportRaidProjectionsNotInitialized = "Logger export raid projections are not initialized"
Diag.A.LoggerExportStoreNotInitialized = "Logger export store is not initialized"
Diag.A.LootSourceCandidateNormalizerNotInitialized = "Loot source candidate normalizer is not initialized"
Diag.A.LootSourceStringHelpersNotInitialized = "Loot source string helpers are not initialized"
Diag.A.LootSourceTestDataLifecycleNotInitialized = "Loot source test data lifecycle is not initialized"
Diag.A.LootSourceTextNormalizerNotInitialized = "Loot source text normalizer is not initialized"
Diag.A.LootSourceTextTrimmerNotInitialized = "Loot source text trimmer is not initialized"
Diag.A.LootSourcesDataActivationSnapshotRequired = "LootSourcesData activation snapshot is required"
Diag.A.MinimapAttendanceControllerNotInitialized = "Minimap attendance controller is not initialized"
Diag.A.MinimapLoggerControllerNotInitialized = "Minimap logger controller is not initialized"
Diag.A.MinimapLootCounterWidgetNotInitialized = "Minimap loot counter widget is not initialized"
Diag.A.MinimapMasterControllerNotInitialized = "Minimap master controller is not initialized"
Diag.A.MinimapPassiveLootObserverNotInitialized = "Minimap passive-loot observer is not initialized"
Diag.A.MinimapRaidCapabilityResolverNotInitialized = "Minimap raid capability resolver is not initialized"
Diag.A.MinimapRaidIconCleanerNotInitialized = "Minimap raid-icon cleaner is not initialized"
Diag.A.MinimapRaidMembershipResolverNotInitialized = "Minimap raid membership resolver is not initialized"
Diag.A.MinimapRaidServiceNotInitialized = "Minimap raid service is not initialized"
Diag.A.MinimapReservesWidgetNotInitialized = "Minimap reserves widget is not initialized"
Diag.A.MinimapSpammerControllerNotInitialized = "Minimap spammer controller is not initialized"
Diag.A.MinimapTooltipHiderNotInitialized = "Minimap tooltip hider is not initialized"
Diag.A.MinimapTooltipPresenterNotInitialized = "Minimap tooltip presenter is not initialized"
Diag.A.MinimapWarningsControllerNotInitialized = "Minimap warnings controller is not initialized"
Diag.A.OptionsLayoutDropdownButtonWidthApiNotInitialized = "Options layout dropdown button width API is not initialized"
Diag.A.OptionsLayoutDropdownWidthApiNotInitialized = "Options layout dropdown width API is not initialized"
Diag.A.RmaGroupPartyCountApiNotInitialized = "RMA Group: party count API is not initialized"
Diag.A.RmaGroupRaidCountApiNotInitialized = "RMA Group: raid count API is not initialized"
Diag.A.RmaGroupUnitExistsApiNotInitialized = "RMA Group: UnitExists API is not initialized"
Diag.A.RmaTimerCreateFrameApiNotInitialized = "RMA Timer: CreateFrame API is not initialized"
Diag.A.RmaTimerGetTimeApiNotInitialized = "RMA Timer: GetTime API is not initialized"
Diag.A.ScreenNoticeEventBusListenerNotInitialized = "Screen notice event bus listener is not initialized"
Diag.A.ScreenNoticeEventNameNotInitialized = "Screen notice event name is not initialized"
Diag.A.ScreenNoticeInternalEventsNotInitialized = "Screen notice internal events are not initialized"
Diag.A.SlashAttendanceControllerNotInitialized = "Slash attendance controller is not initialized"
Diag.A.SlashLoggerControllerNotInitialized = "Slash logger controller is not initialized"
Diag.A.SlashLootCounterWidgetNotInitialized = "Slash loot counter widget is not initialized"
Diag.A.SlashMasterControllerNotInitialized = "Slash master controller is not initialized"
Diag.A.SlashReservesAliasListerNotInitialized = "Slash reserves alias lister is not initialized"
Diag.A.SlashReservesAliasRemoverNotInitialized = "Slash reserves alias remover is not initialized"
Diag.A.SlashReservesAliasSetterNotInitialized = "Slash reserves alias setter is not initialized"
Diag.A.SlashReservesCountResolverNotInitialized = "Slash reserves count resolver is not initialized"
Diag.A.SlashReservesReadinessReporterNotInitialized = "Slash reserves readiness reporter is not initialized"
Diag.A.SlashReservesServiceNotInitialized = "Slash reserves service is not initialized"
Diag.A.SlashReservesSyncCacheCleanerNotInitialized = "Slash reserves sync cache cleaner is not initialized"
Diag.A.SlashReservesSyncMetadataReaderNotInitialized = "Slash reserves sync metadata reader is not initialized"
Diag.A.SlashReservesSyncRequesterNotInitialized = "Slash reserves sync requester is not initialized"
Diag.A.SlashReservesWidgetNotInitialized = "Slash reserves widget is not initialized"
Diag.A.SlashSoftresItemIdResolverNotInitialized = "Slash softres item-id resolver is not initialized"
Diag.A.SlashSoftresLootItemResolverNotInitialized = "Slash softres loot item resolver is not initialized"
Diag.A.SlashSoftresLootServiceNotInitialized = "Slash softres loot service is not initialized"
Diag.A.SlashSpammerControllerNotInitialized = "Slash spammer controller is not initialized"
Diag.A.SlashWarningsControllerNotInitialized = "Slash warnings controller is not initialized"
Diag.A.SpecInspectCoordinatorNotInitialized = "SpecInspect coordinator is not initialized"
Diag.A.SpecInspectEventBusListenerNotInitialized = "SpecInspect event bus listener is not initialized"
Diag.A.SpecInspectEventPublisherNotInitialized = "SpecInspect event publisher is not initialized"
Diag.A.SpecInspectInternalEventsNotInitialized = "SpecInspect internal events are not initialized"
Diag.A.SpecInspectNameNormalizerNotInitialized = "SpecInspect name normalizer is not initialized"
Diag.A.SpecInspectReadyCheckEventNotInitialized = "SpecInspect ready-check event is not initialized"
Diag.A.SpecInspectTimeApiNotInitialized = "SpecInspect time API is not initialized"
Diag.A.SpecInspectUnitGuidApiNotInitialized = "SpecInspect unit GUID API is not initialized"
Diag.A.SpecInspectUpdateEventNotInitialized = "SpecInspect update event is not initialized"
Diag.A.TimerDebugEntrypointNotInitialized = "Timer debug entrypoint is not initialized"
Diag.A.UiCombatLockdownApiNotInitialized = "UI combat-lockdown API is not initialized"
Diag.A.UiEditBoxTextNormalizerNotInitialized = "UI edit-box text normalizer is not initialized"
Diag.A.UiFrameCreationApiNotInitialized = "UI frame creation API is not initialized"
Diag.A.WarningsStoreDataChangedEventNotInitialized = "Warnings store data-changed event is not initialized"
Diag.A.WarningsStoreEventPublisherNotInitialized = "Warnings store event publisher is not initialized"
Diag.A.WarningsStoreInternalEventsNotInitialized = "Warnings store internal events are not initialized"

-- Raid --
Diag.A.DebugModeNormalizerNotInitialized = "Debug mode normalizer is not initialized"
Diag.A.DebugSyntheticNameNormalizerNotInitialized = "Debug synthetic name normalizer is not initialized"
Diag.A.LootContextOwnerNotInitialized = "Loot context owner is not initialized"
Diag.A.LootContextStateOwnerNotInitialized = "Loot context state owner is not initialized"
Diag.A.LootSessionOwnerNotInitialized = "Loot session owner is not initialized"
Diag.A.LootSnapshotOwnerNotInitialized = "Loot snapshot owner is not initialized"
Diag.A.RaidAttendanceChangedEventNotInitialized = "Raid attendance changed event is not initialized"
Diag.A.RaidAttendanceEventBusListenerNotInitialized = "Raid attendance event bus listener is not initialized"
Diag.A.RaidAttendanceEventPublisherNotInitialized = "Raid attendance event publisher is not initialized"
Diag.A.RaidAttendanceInternalEventsNotInitialized = "Raid attendance internal events are not initialized"
Diag.A.RaidAttendanceRaidCreateEventNotInitialized = "Raid attendance raid-create event is not initialized"
Diag.A.RaidAttendanceRosterCountApiNotInitialized = "Raid attendance roster count API is not initialized"
Diag.A.RaidAttendanceRosterDeltaEventNotInitialized = "Raid attendance roster-delta event is not initialized"
Diag.A.RaidAttendanceRosterInfoApiNotInitialized = "Raid attendance roster info API is not initialized"
Diag.A.RaidAuthorityRecoveryEventNotInitialized = "Raid authority recovery event is not initialized"
Diag.A.RaidCapabilityGroupRankResolverNotInitialized = "Raid capability group-rank resolver is not initialized"
Diag.A.RaidCapabilityLootMethodApiNotInitialized = "Raid capability loot-method API is not initialized"
Diag.A.RaidCapabilityNameNormalizerNotInitialized = "Raid capability name normalizer is not initialized"
Diag.A.RaidCapabilityRaidMembershipResolverNotInitialized = "Raid capability raid-membership resolver is not initialized"
Diag.A.RaidCapabilityRosterApiNotInitialized = "Raid capability roster API is not initialized"
Diag.A.RaidCapabilityRosterCountApiNotInitialized = "Raid capability roster count API is not initialized"
Diag.A.RaidCapabilityUnitComparisonApiNotInitialized = "Raid capability unit comparison API is not initialized"
Diag.A.RaidCapabilityUnitNameApiNotInitialized = "Raid capability unit-name API is not initialized"
Diag.A.RaidCapabilityUnitResolverNotInitialized = "Raid capability unit resolver is not initialized"
Diag.A.RaidCountsEventPublisherNotInitialized = "Raid counts event publisher is not initialized"
Diag.A.RaidCountsInternalEventsNotInitialized = "Raid counts internal events are not initialized"
Diag.A.RaidCountsPlayerCountEventNotInitialized = "Raid counts player-count event is not initialized"
Diag.A.RaidDebugEntrypointNotInitialized = "Raid debug entrypoint is not initialized"
Diag.A.RaidLootMethodCreatureIdHelperNotInitialized = "Raid loot method creature-id helper is not initialized"
Diag.A.RaidLootMethodEventBusSenderNotInitialized = "Raid loot method event bus sender is not initialized"
Diag.A.RaidLootMethodEventRegistryNotInitialized = "Raid loot method event registry is not initialized"
Diag.A.RaidLootMethodRestoreNotificationNotInitialized = "Raid loot method restore notification is not initialized"
Diag.A.RaidLootMethodScreenNoticeEventNotInitialized = "Raid loot method screen notice event is not initialized"
Diag.A.RaidLootMethodServiceOwnerNotInitialized = "Raid loot method service owner is not initialized"
Diag.A.RaidLootMethodSetterApiNotInitialized = "Raid loot method setter API is not initialized"
Diag.A.RaidLootMethodTimeApiNotInitialized = "Raid loot method time API is not initialized"
Diag.A.RaidLootMethodUnitDeathStateApiNotInitialized = "Raid loot method unit death-state API is not initialized"
Diag.A.RaidLootMethodUnitExistenceApiNotInitialized = "Raid loot method unit existence API is not initialized"
Diag.A.RaidLootMethodUnitGuidApiNotInitialized = "Raid loot method unit GUID API is not initialized"
Diag.A.RaidLootMethodUnitNameApiNotInitialized = "Raid loot method unit name API is not initialized"
Diag.A.RaidLootMethodUnitRaidMembershipApiNotInitialized = "Raid loot method unit raid-membership API is not initialized"
Diag.A.RaidReEntryDecisionRequiredEventNotInitialized = "Raid re-entry decision-required event is not initialized"
Diag.A.RaidReEntryDecisionResolvedEventNotInitialized = "Raid re-entry decision-resolved event is not initialized"
Diag.A.RaidReEntryRecoveryEventNotInitialized = "Raid re-entry recovery event is not initialized"
Diag.A.RaidRosterCancellationNotInitialized = "Raid roster cancellation is not initialized"
Diag.A.RaidRosterCountApiNotInitialized = "Raid roster count API is not initialized"
Diag.A.RaidRosterDeltaEventNotInitialized = "Raid roster delta event is not initialized"
Diag.A.RaidRosterEventPublisherNotInitialized = "Raid roster event publisher is not initialized"
Diag.A.RaidRosterInternalEventsNotInitialized = "Raid roster internal events are not initialized"
Diag.A.RaidRosterSchedulerNotInitialized = "Raid roster scheduler is not initialized"
Diag.A.RaidServiceNamespaceNotInitialized = "Raid service namespace is not initialized"
Diag.A.RaidSessionTargetIconApiNotInitialized = "Raid session target icon API is not initialized"
Diag.A.RaidStateAttendanceEventNotInitialized = "Raid state attendance event is not initialized"
Diag.A.RaidStateEventListenerNotInitialized = "Raid state event listener is not initialized"
Diag.A.RaidStateEventPublisherNotInitialized = "Raid state event publisher is not initialized"
Diag.A.RaidStateGroupHelperOwnerNotInitialized = "Raid state group helper owner is not initialized"
Diag.A.RaidStateGroupPolicyHelperNotInitialized = "Raid state group policy helper is not initialized"
Diag.A.RaidStateInstanceInfoApiNotInitialized = "Raid state instance info API is not initialized"
Diag.A.RaidStateInternalEventsNotInitialized = "Raid state internal events are not initialized"
Diag.A.RaidStateLootNamespaceNotInitialized = "Raid state loot namespace is not initialized"
Diag.A.RaidStateRaidCreateEventNotInitialized = "Raid state raid-create event is not initialized"
Diag.A.RaidStateRosterCountApiNotInitialized = "Raid state roster count API is not initialized"
Diag.A.RaidStateUnitNameApiNotInitialized = "Raid state unit name API is not initialized"
Diag.A.RaidUnknownNameHelperNotInitialized = "Raid unknown-name helper is not initialized"

-- Loot --
Diag.A.LootAttributionOwnerNotInitialized = "Loot attribution owner is not initialized"
Diag.A.LootAwardPlannerOwnerNotInitialized = "Loot award planner owner is not initialized"
Diag.A.LootContextCurrentRaidResolverNotInitialized = "Loot context current-raid resolver is not initialized"
Diag.A.LootContextHelpersNotInitialized = "Loot context helpers are not initialized"
Diag.A.LootContextRaidResolverNotInitialized = "Loot context raid resolver is not initialized"
Diag.A.LootContextRaidSchemaNormalizerNotInitialized = "Loot context raid schema normalizer is not initialized"
Diag.A.LootContextStateRequiresRaidStateTable = "Loot context state requires raidState table"
Diag.A.LootContextTextNormalizerNotInitialized = "Loot context text normalizer is not initialized"
Diag.A.LootDistributionAuthorityResolverNotInitialized = "Loot distribution authority resolver is not initialized"
Diag.A.LootDistributionBatchSenderNotInitialized = "Loot distribution batch sender is not initialized"
Diag.A.LootDistributionChangeEventNotInitialized = "Loot distribution change event is not initialized"
Diag.A.LootDistributionDirectSenderNotInitialized = "Loot distribution direct sender is not initialized"
Diag.A.LootDistributionEventBusSenderNotInitialized = "Loot distribution event bus sender is not initialized"
Diag.A.LootDistributionGroupMembershipResolverNotInitialized = "Loot distribution group-membership resolver is not initialized"
Diag.A.LootDistributionGroupSenderNotInitialized = "Loot distribution group sender is not initialized"
Diag.A.LootDistributionInternalEventsNotInitialized = "Loot distribution internal events are not initialized"
Diag.A.LootDistributionItemKeyResolverNotInitialized = "Loot distribution item-key resolver is not initialized"
Diag.A.LootDistributionPayloadCodecNotInitialized = "Loot distribution payload codec is not initialized"
Diag.A.LootDistributionPlayerNameNotInitialized = "Loot distribution player name is not initialized"
Diag.A.LootDistributionPlayerNameResolverNotInitialized = "Loot distribution player-name resolver is not initialized"
Diag.A.LootDistributionRaidCapabilityResolverNotInitialized = "Loot distribution raid capability resolver is not initialized"
Diag.A.LootDistributionRaidServiceNotInitialized = "Loot distribution raid service is not initialized"
Diag.A.LootDistributionSessionOwnerNotInitialized = "Loot distribution session owner is not initialized"
Diag.A.LootDistributionTimeApiNotInitialized = "Loot distribution time API is not initialized"
Diag.A.LootDistributionTimeApiReturnedInvalidTimestamp = "Loot distribution time API returned invalid timestamp"
Diag.A.LootDistributionTimeInvalid = "Loot distribution time is invalid"
Diag.A.LootInventoryContainerItemInfoApiNotInitialized = "Loot inventory container item info API is not initialized"
Diag.A.LootInventoryContainerItemLinkApiNotInitialized = "Loot inventory container item link API is not initialized"
Diag.A.LootInventoryContainerSlotCountApiNotInitialized = "Loot inventory container slot count API is not initialized"
Diag.A.LootInventoryLootCountApiNotInitialized = "Loot inventory loot count API is not initialized"
Diag.A.LootInventoryLootSlotLinkApiNotInitialized = "Loot inventory loot slot link API is not initialized"
Diag.A.LootInventoryOwnerNotInitialized = "Loot inventory owner is not initialized"
Diag.A.LootLoggerQualityThresholdNormalizerNotInitialized = "Loot logger quality threshold normalizer is not initialized"
Diag.A.LootPassiveGroupLootHelpersNotInitialized = "Loot passive group-loot helpers are not initialized"
Diag.A.LootRecordTimestampNotInitialized = "Loot record timestamp is not initialized"
Diag.A.LootRecordingHelpersNotInitialized = "Loot recording helpers are not initialized"
Diag.A.LootRecordingItemKeyResolverNotInitialized = "Loot recording item-key resolver is not initialized"
Diag.A.LootRecordingItemStringResolverNotInitialized = "Loot recording item-string resolver is not initialized"
Diag.A.LootRecordingNameNormalizerNotInitialized = "Loot recording name normalizer is not initialized"
Diag.A.LootRecordingTimeProviderNotInitialized = "Loot recording time provider is not initialized"
Diag.A.LootRulesEnchantingMaterialDatasetNotInitialized = "Loot rules enchanting-material dataset is not initialized"
Diag.A.LootRulesHelpersNotInitialized = "Loot rules helpers are not initialized"
Diag.A.LootRulesIgnoredItemDatasetNotInitialized = "Loot rules ignored-item dataset is not initialized"
Diag.A.LootRulesIgnoredItemsNamespaceNotInitialized = "Loot rules ignored-items namespace is not initialized"
Diag.A.LootRulesItemIdResolverNotInitialized = "Loot rules item-id resolver is not initialized"
Diag.A.LootRulesItemInfoApiNotInitialized = "Loot rules item info API is not initialized"
Diag.A.LootRulesTooltipBindResolverNotInitialized = "Loot rules tooltip bind resolver is not initialized"
Diag.A.LootServiceDistributionEventNotInitialized = "Loot service distribution event is not initialized"
Diag.A.LootServiceEventPublisherNotInitialized = "Loot service event publisher is not initialized"
Diag.A.LootServiceInternalEventsNotInitialized = "Loot service internal events are not initialized"
Diag.A.LootServiceLootThresholdApiNotInitialized = "Loot service loot-threshold API is not initialized"
Diag.A.LootServiceRaidLootUpdateEventNotInitialized = "Loot service raid-loot update event is not initialized"
Diag.A.LootServiceSelectedItemEventNotInitialized = "Loot service selected-item event is not initialized"
Diag.A.LootSnapshotItemKeyResolverNotInitialized = "Loot snapshot item-key resolver is not initialized"
Diag.A.LootStateHelpersNotInitialized = "Loot state helpers are not initialized"
Diag.A.LootStateTimeApiNotInitialized = "Loot state time API is not initialized"
Diag.A.LootTrackingGroupCountHelperNotInitialized = "Loot tracking group-count helper is not initialized"
Diag.A.LootTrackingGroupHelperOwnerNotInitialized = "Loot tracking group helper owner is not initialized"
Diag.A.LootTrackingHelpersNotInitialized = "Loot tracking helpers are not initialized"
Diag.A.LootTrackingLootMethodApiNotInitialized = "Loot tracking loot-method API is not initialized"
Diag.A.LootTrackingMasterLootCandidateApiNotInitialized = "Loot tracking master-loot candidate API is not initialized"
Diag.A.LootWorkflowHelpersNotInitialized = "Loot workflow helpers are not initialized"
Diag.A.MissingLootAttributionNormalizePendingAwardItemKey = "Missing LootAttribution.NormalizePendingAwardItemKey"
Diag.A.MissingLootContextBuildActiveLootContext = "Missing LootContext.BuildActiveLootContext"
Diag.A.MissingLootContextNormalizeActiveLootContext = "Missing LootContext.NormalizeActiveLootContext"
Diag.A.MissingLootContextNormalizeBossEventContext = "Missing LootContext.NormalizeBossEventContext"
Diag.A.MissingLootContextNormalizeLootSessionState = "Missing LootContext.NormalizeLootSessionState"
Diag.A.MissingLootContextNormalizeLootSnapshotState = "Missing LootContext.NormalizeLootSnapshotState"
Diag.A.MissingLootContextProjectLootSourceState = "Missing LootContext.ProjectLootSourceState"
Diag.A.MissingLootContextProjectLootWindowBossContext = "Missing LootContext.ProjectLootWindowBossContext"
Diag.A.MissingLootContextResolveRaidRecord = "Missing LootContext.ResolveRaidRecord"
Diag.A.MissingLootRulesIsIgnoredItem = "Missing LootRules._IsIgnoredItem"
Diag.A.PassiveGroupLootItemKeyResolverNotInitialized = "Passive group-loot item-key resolver is not initialized"
Diag.A.PassiveGroupLootMethodPolicyResolverNotInitialized = "Passive group-loot method policy resolver is not initialized"
Diag.A.PassiveGroupLootRaidServiceNotInitialized = "Passive group-loot raid service is not initialized"
Diag.A.PassiveGroupLootRollItemInfoApiNotInitialized = "Passive group-loot roll item info API is not initialized"
Diag.A.PassiveGroupLootRollItemLinkApiNotInitialized = "Passive group-loot roll item link API is not initialized"

-- Master --
Diag.A.AwardConfirmationRequiresAnEffect = "Award confirmation requires an effect"
Diag.A.MasterAwardAttemptFactoryNotInitialized = "Master award attempt factory is not initialized"
Diag.A.MasterAwardAwardedItemRecorderNotInitialized = "Master award awarded-item recorder is not initialized"
Diag.A.MasterAwardConfirmationRequiresFunction = "Award confirmation requires %s"
Diag.A.MasterAwardExecutorNotInitialized = "Master award executor is not initialized"
Diag.A.MasterAwardInventoryOwnerNotInitialized = "Master award inventory owner is not initialized"
Diag.A.MasterAwardItemCountOwnerNotInitialized = "Master award item-count owner is not initialized"
Diag.A.MasterAwardItemKeyResolverNotInitialized = "Master award item-key resolver is not initialized"
Diag.A.MasterAwardLootBansOwnerNotInitialized = "Master award loot bans owner is not initialized"
Diag.A.MasterAwardLootServiceNotInitialized = "Master award loot service is not initialized"
Diag.A.MasterAwardLootStateNotInitialized = "Master award loot state is not initialized"
Diag.A.MasterAwardPlannerNotInitialized = "Master award planner is not initialized"
Diag.A.MasterAwardRaidResolverNotInitialized = "Master award raid resolver is not initialized"
Diag.A.MasterAwardRaidServiceNotInitialized = "Master award raid service is not initialized"
Diag.A.MasterAwardRollSelectionOwnerNotInitialized = "Master award roll selection owner is not initialized"
Diag.A.MasterAwardRollSessionResolverNotInitialized = "Master award roll-session resolver is not initialized"
Diag.A.MasterAwardTimerCancellerNotInitialized = "Master award timer canceller is not initialized"
Diag.A.MasterAwardTimerSchedulerNotInitialized = "Master award timer scheduler is not initialized"
Diag.A.MasterItemSelectionClearCursorApiNotInitialized = "Master item selection clear-cursor API is not initialized"
Diag.A.MasterItemSelectionContainerItemLinkApiNotInitialized = "Master item selection container-item-link API is not initialized"
Diag.A.MasterItemSelectionCursorInfoApiNotInitialized = "Master item selection cursor-info API is not initialized"
Diag.A.MasterItemSelectionCursorItemApiNotInitialized = "Master item selection cursor-item API is not initialized"
Diag.A.MasterRollSelectionDisplayModelResolverNotInitialized = "Master RollSelection display model resolver is not initialized"
Diag.A.MasterRollSelectionRowModelOwnerNotInitialized = "Master RollSelection row model owner is not initialized"
Diag.A.MasterRollSelectionSelectionOwnerNotInitialized = "Master RollSelection selection owner is not initialized"
Diag.A.MasterRollSelectionStateTableNotInitialized = "Master RollSelection state table is not initialized"
Diag.A.MasterServiceNamespaceNotInitialized = "Master service namespace is not initialized"
Diag.A.MasterTradeAwardAttemptFactoryNotInitialized = "Master trade award-attempt factory is not initialized"
Diag.A.MasterTradeExecutionAnnounceStateGetterNotInitialized = "Master trade execution announce-state getter is not initialized"
Diag.A.MasterTradeExecutionAnnounceStateSetterNotInitialized = "Master trade execution announce-state setter is not initialized"
Diag.A.MasterTradeExecutionAnnouncerNotInitialized = "Master trade execution announcer is not initialized"
Diag.A.MasterTradeExecutionAwardPlannerNotInitialized = "Master trade execution award planner is not initialized"
Diag.A.MasterTradeExecutionAwardedItemRecorderNotInitialized = "Master trade execution awarded-item recorder is not initialized"
Diag.A.MasterTradeExecutionClearCursorApiNotInitialized = "Master trade execution clear-cursor API is not initialized"
Diag.A.MasterTradeExecutionCommsServiceNotInitialized = "Master trade execution comms service is not initialized"
Diag.A.MasterTradeExecutionContainerItemInfoApiNotInitialized = "Master trade execution container-item-info API is not initialized"
Diag.A.MasterTradeExecutionContainerItemLinkApiNotInitialized = "Master trade execution container-item-link API is not initialized"
Diag.A.MasterTradeExecutionCursorItemApiNotInitialized = "Master trade execution cursor-item API is not initialized"
Diag.A.MasterTradeExecutionDatabaseHelpersNotInitialized = "Master trade execution database helpers are not initialized"
Diag.A.MasterTradeExecutionDistributionOwnerNotInitialized = "Master trade execution distribution owner is not initialized"
Diag.A.MasterTradeExecutionErrorReporterNotInitialized = "Master trade execution error reporter is not initialized"
Diag.A.MasterTradeExecutionInitiateTradeApiNotInitialized = "Master trade execution initiate-trade API is not initialized"
Diag.A.MasterTradeExecutionInteractDistanceApiNotInitialized = "Master trade execution interact-distance API is not initialized"
Diag.A.MasterTradeExecutionInventoryOwnerNotInitialized = "Master trade execution inventory owner is not initialized"
Diag.A.MasterTradeExecutionItemHelpersNotInitialized = "Master trade execution item helpers are not initialized"
Diag.A.MasterTradeExecutionItemStateNotInitialized = "Master trade execution item state is not initialized"
Diag.A.MasterTradeExecutionLoggerRequestHelperNotInitialized = "Master trade execution logger request helper is not initialized"
Diag.A.MasterTradeExecutionLootBansOwnerNotInitialized = "Master trade execution Loot Bans owner is not initialized"
Diag.A.MasterTradeExecutionLootContextResolverNotInitialized = "Master trade execution loot-context resolver is not initialized"
Diag.A.MasterTradeExecutionLootResetHelperNotInitialized = "Master trade execution loot-reset helper is not initialized"
Diag.A.MasterTradeExecutionLootServiceNotInitialized = "Master trade execution loot service is not initialized"
Diag.A.MasterTradeExecutionLootStateNotInitialized = "Master trade execution loot state is not initialized"
Diag.A.MasterTradeExecutionOptionGetterNotInitialized = "Master trade execution option getter is not initialized"
Diag.A.MasterTradeExecutionPickupContainerItemApiNotInitialized = "Master trade execution pickup-container-item API is not initialized"
Diag.A.MasterTradeExecutionRaidServiceNotInitialized = "Master trade execution raid service is not initialized"
Diag.A.MasterTradeExecutionRaidTargetApiNotInitialized = "Master trade execution raid-target API is not initialized"
Diag.A.MasterTradeExecutionRefreshHookNotInitialized = "Master trade execution refresh hook is not initialized"
Diag.A.MasterTradeExecutionRollModelBuilderNotInitialized = "Master trade execution roll-model builder is not initialized"
Diag.A.MasterTradeExecutionRollSelectionOwnerNotInitialized = "Master trade execution roll selection owner is not initialized"
Diag.A.MasterTradeExecutionRollSessionOptionsBuilderNotInitialized = "Master trade execution roll-session options builder is not initialized"
Diag.A.MasterTradeExecutionRollsServiceNotInitialized = "Master trade execution rolls service is not initialized"
Diag.A.MasterTradeExecutionScreenshotWarningGetterNotInitialized = "Master trade execution screenshot-warning getter is not initialized"
Diag.A.MasterTradeExecutionScreenshotWarningSetterNotInitialized = "Master trade execution screenshot-warning setter is not initialized"
Diag.A.MasterTradeExecutionTradeMenuHiderNotInitialized = "Master trade execution trade-menu hider is not initialized"
Diag.A.MasterTradeExecutionTradeOwnerNotInitialized = "Master trade execution trade owner is not initialized"
Diag.A.MasterTradeExecutionTradeStateResetNotInitialized = "Master trade execution trade-state reset is not initialized"
Diag.A.MasterTradeExecutionWoWApiTableNotInitialized = "Master trade execution WoW API table is not initialized"
Diag.A.MasterTradeInventoryOwnerNotInitialized = "Master trade inventory owner is not initialized"
Diag.A.MasterTradeItemKeyResolverNotInitialized = "Master trade item-key resolver is not initialized"
Diag.A.MasterTradeLoggerActionsServiceNotInitialized = "Master trade logger actions service is not initialized"
Diag.A.MasterTradeRaidHistoryAuthorityResolverNotInitialized = "Master trade raid-history authority resolver is not initialized"

-- Rolls --
Diag.A.RollHistoryAddRollEventNotInitialized = "Roll history add-roll event is not initialized"
Diag.A.RollHistoryEventPublisherNotInitialized = "Roll history event publisher is not initialized"
Diag.A.RollHistoryInternalEventsNotInitialized = "Roll history internal events are not initialized"
Diag.A.RollResponseLootBansOwnerNotInitialized = "Roll response loot bans owner is not initialized"
Diag.A.RollResponseNameNormalizerNotInitialized = "Roll response name normalizer is not initialized"
Diag.A.RollResponseRaidServiceNotInitialized = "Roll response raid service is not initialized"
Diag.A.RollSessionCandidateNormalizerNotInitialized = "Roll session candidate normalizer is not initialized"
Diag.A.RollsCountdownHelpersNotInitialized = "Rolls countdown helpers are not initialized"
Diag.A.RollsDisplayContextRequired = "Rolls display context is required"
Diag.A.RollsDisplayCurrentRollContextRequired = "Rolls display current-roll context is required"
Diag.A.RollsDisplayHelpersNotInitialized = "Rolls display helpers are not initialized"
Diag.A.RollsDisplayLootStateRequired = "Rolls display loot state is required"
Diag.A.RollsDisplayStateRequired = "Rolls display state is required"
Diag.A.RollsHistoryContextRequired = "Rolls history context is required"
Diag.A.RollsHistoryHelpersNotInitialized = "Rolls history helpers are not initialized"
Diag.A.RollsHistoryLootStateRequired = "Rolls history loot state is required"
Diag.A.RollsHistoryStateRequired = "Rolls history state is required"
Diag.A.RollsLootStateRequired = "Rolls loot state is required"
Diag.A.RollsResolutionContextRequired = "Rolls resolution context is required"
Diag.A.RollsResolutionHelpersNotInitialized = "Rolls resolution helpers are not initialized"
Diag.A.RollsResolutionStateRequired = "Rolls resolution state is required"
Diag.A.RollsResponseContextRequired = "Rolls response context is required"
Diag.A.RollsResponseHelpersNotInitialized = "Rolls response helpers are not initialized"
Diag.A.RollsResponseStateRequired = "Rolls response state is required"
Diag.A.RollsSessionHelpersNotInitialized = "Rolls session helpers are not initialized"
Diag.A.RollsSessionStateRequired = "Rolls session state is required"
Diag.A.RollsSessionsContextRequired = "Rolls sessions context is required"
Diag.A.RollsStrategyHelpersNotInitialized = "Rolls strategy helpers are not initialized"

-- Reserves --
Diag.A.MissingReservesImportParser = "Missing Reserves import parser"
Diag.A.ReservesAliasHelpersNotInitialized = "Reserves alias helpers are not initialized"
Diag.A.ReservesAliasKeyNormalizerNotInitialized = "Reserves alias key normalizer is not initialized"
Diag.A.ReservesCanonicalNameNormalizerNotInitialized = "Reserves canonical name normalizer is not initialized"
Diag.A.ReservesChatAddReserveHandlerNotInitialized = "Reserves chat add-reserve handler is not initialized"
Diag.A.ReservesChatClockNotInitialized = "Reserves chat clock is not initialized"
Diag.A.ReservesChatEventBusListenerNotInitialized = "Reserves chat event bus listener is not initialized"
Diag.A.ReservesChatIdentityNormalizerNotInitialized = "Reserves chat identity normalizer is not initialized"
Diag.A.ReservesChatImportModeResolverNotInitialized = "Reserves chat import-mode resolver is not initialized"
Diag.A.ReservesChatPlayerIdentityResolverNotInitialized = "Reserves chat player identity resolver is not initialized"
Diag.A.ReservesChatPlayerReserveLookupNotInitialized = "Reserves chat player-reserve lookup is not initialized"
Diag.A.ReservesChatRaidCapabilityResolverNotInitialized = "Reserves chat raid capability resolver is not initialized"
Diag.A.ReservesChatRaidRoleResolverNotInitialized = "Reserves chat raid-role resolver is not initialized"
Diag.A.ReservesChatRaidServiceNotInitialized = "Reserves chat raid service is not initialized"
Diag.A.ReservesChatRealmResolverNotInitialized = "Reserves chat realm resolver is not initialized"
Diag.A.ReservesChatReserveCountLookupNotInitialized = "Reserves chat reserve-count lookup is not initialized"
Diag.A.ReservesChatThrottleSchedulerNotInitialized = "Reserves chat throttle scheduler is not initialized"
Diag.A.ReservesChatWhisperEventNameNotInitialized = "Reserves chat whisper event name is not initialized"
Diag.A.ReservesChatWhisperTransportNotInitialized = "Reserves chat whisper transport is not initialized"
Diag.A.ReservesDataChangedEventNotInitialized = "Reserves data-changed event is not initialized"
Diag.A.ReservesDisplayHelpersNotInitialized = "Reserves display helpers are not initialized"
Diag.A.ReservesDisplayNameNormalizerNotInitialized = "Reserves display name normalizer is not initialized"
Diag.A.ReservesEventPublisherNotInitialized = "Reserves event publisher is not initialized"
Diag.A.ReservesImportHelpersNotInitialized = "Reserves import helpers are not initialized"
Diag.A.ReservesInternalEventsNotInitialized = "Reserves internal events are not initialized"
Diag.A.ReservesItemInfoApiNotInitialized = "Reserves item info API is not initialized"
Diag.A.ReservesSyncAuthorityResolverNotInitialized = "Reserves sync authority resolver is not initialized"
Diag.A.ReservesSyncBatchTransportNotInitialized = "Reserves sync batch transport is not initialized"
Diag.A.ReservesSyncDirectTransportNotInitialized = "Reserves sync direct transport is not initialized"
Diag.A.ReservesSyncGroupMembershipResolverNotInitialized = "Reserves sync group-membership resolver is not initialized"
Diag.A.ReservesSyncGroupTransportNotInitialized = "Reserves sync group transport is not initialized"
Diag.A.ReservesSyncPlayerNormalizerNotInitialized = "Reserves sync player normalizer is not initialized"
Diag.A.ReservesSyncRaidRoleResolverNotInitialized = "Reserves sync raid-role resolver is not initialized"
Diag.A.ReservesSyncRaidServiceNotInitialized = "Reserves sync raid service is not initialized"
Diag.A.ReservesSyncSenderNormalizerNotInitialized = "Reserves sync sender normalizer is not initialized"
Diag.A.ReservesSyncTimeApiNotInitialized = "Reserves sync time API is not initialized"
Diag.A.ReservesSyncUnitNameApiNotInitialized = "Reserves sync unit name API is not initialized"

-- Controllers --
Diag.A.AttendanceActionsServiceNotInitialized = "Attendance actions service is not initialized"
Diag.A.AttendanceColumnLayoutOwnerNotInitialized = "Attendance column layout owner is not initialized"
Diag.A.AttendanceControllerEquipInspectCompletionEventNotInitialized = "Attendance controller equip inspect completion event is not initialized"
Diag.A.AttendanceControllerEquipInspectUpdateEventNotInitialized = "Attendance controller equip inspect update event is not initialized"
Diag.A.AttendanceControllerEventListenerNotInitialized = "Attendance controller event listener is not initialized"
Diag.A.AttendanceControllerEventPublisherNotInitialized = "Attendance controller event publisher is not initialized"
Diag.A.AttendanceControllerInternalEventsNotInitialized = "Attendance controller internal events are not initialized"
Diag.A.AttendanceControllerLoggerSelectionClearEventNotInitialized = "Attendance controller logger selection-clear event is not initialized"
Diag.A.AttendanceControllerRaidAttendanceChangedEventNotInitialized = "Attendance controller raid attendance changed event is not initialized"
Diag.A.AttendanceControllerRaidCreateEventNotInitialized = "Attendance controller raid-create event is not initialized"
Diag.A.AttendanceEquipInspectServiceNotInitialized = "Attendance equip-inspect service is not initialized"
Diag.A.AttendanceExportDialogOwnerNotInitialized = "Attendance export dialog owner is not initialized"
Diag.A.AttendanceExportServiceNotInitialized = "Attendance export service is not initialized"
Diag.A.AttendanceForceInspectMethodNotInitialized = "Attendance force-inspect method is not initialized"
Diag.A.AttendanceFrameCreationApiNotInitialized = "Attendance frame creation API is not initialized"
Diag.A.AttendanceFrameGetterFactoryNotInitialized = "Attendance frame getter factory is not initialized"
Diag.A.AttendanceFrameRefResolverNotInitialized = "Attendance frame ref resolver is not initialized"
Diag.A.AttendanceFrameScriptBinderNotInitialized = "Attendance frame script binder is not initialized"
Diag.A.AttendanceFrameTitleBinderNotInitialized = "Attendance frame title binder is not initialized"
Diag.A.AttendanceItemTooltipRendererNotInitialized = "Attendance item tooltip renderer is not initialized"
Diag.A.AttendanceLootBanEventNotInitialized = "Attendance Loot Ban event is not initialized"
Diag.A.AttendanceLootBanOwnerNotInitialized = "Attendance Loot Ban owner is not initialized"
Diag.A.AttendanceModuleFrameBinderNotInitialized = "Attendance module frame binder is not initialized"
Diag.A.AttendanceRaidProjectionsServiceNotInitialized = "Attendance raid projections service is not initialized"
Diag.A.AttendanceRaidServiceNotInitialized = "Attendance raid service is not initialized"
Diag.A.AttendanceServiceNamespaceNotInitialized = "Attendance service namespace is not initialized"
Diag.A.AttendanceStoreServiceNotInitialized = "Attendance store service is not initialized"
Diag.A.AttendanceTooltipHideServiceNotInitialized = "Attendance tooltip hide service is not initialized"
Diag.A.AttendanceTooltipLineRendererNotInitialized = "Attendance tooltip line renderer is not initialized"
Diag.A.AttendanceTooltipModelBinderNotInitialized = "Attendance tooltip model binder is not initialized"
Diag.A.AttendanceViewServiceNotInitialized = "Attendance view service is not initialized"
Diag.A.ConfigConfirmPopupShowerNotInitialized = "Config confirm popup shower is not initialized"
Diag.A.ConfigDebugEntrypointNotInitialized = "Config debug entrypoint is not initialized"
Diag.A.ConfigDebugOptionSetterNotInitialized = "Config debug option setter is not initialized"
Diag.A.ConfigEventBusListenerNotInitialized = "Config event bus listener is not initialized"
Diag.A.ConfigEventBusSenderNotInitialized = "Config event bus sender is not initialized"
Diag.A.ConfigInterfaceOptionsRegistrationApiNotInitialized = "Config interface options registration API is not initialized"
Diag.A.ConfigInternalEventsNotInitialized = "Config internal events are not initialized"
Diag.A.ConfigOptionChangeEventResolverNotInitialized = "Config option-change event resolver is not initialized"
Diag.A.ConfigOptionsLayoutOwnerNotInitialized = "Config options layout owner is not initialized"
Diag.A.ConfigOptionsLoadedEventNotInitialized = "Config options-loaded event is not initialized"
Diag.A.ConfigOptionsResetOperationNotInitialized = "Config options reset operation is not initialized"
Diag.A.ConfigOptionsRowLayoutApplierNotInitialized = "Config options row layout applier is not initialized"
Diag.A.ConfigPopupNamespaceNotInitialized = "Config popup namespace is not initialized"
Diag.A.ConfigSpammerControllerNotInitialized = "Config spammer controller is not initialized"
Diag.A.ConfigSpammerDraftServiceNotInitialized = "Config spammer draft service is not initialized"
Diag.A.ConfigWarningsControllerNotInitialized = "Config warnings controller is not initialized"
Diag.A.ConfigWarningsStoreServiceNotInitialized = "Config warnings store service is not initialized"
Diag.A.LoggerActionsServiceNotInitialized = "Logger actions service is not initialized"
Diag.A.LoggerColumnLayoutOwnerNotInitialized = "Logger column layout owner is not initialized"
Diag.A.LoggerConfirmPopupShowerNotInitialized = "Logger confirm popup shower is not initialized"
Diag.A.LoggerControllerBossPlayerSelectionEventNotInitialized = "Logger controller boss-player selection event is not initialized"
Diag.A.LoggerControllerBossSelectionEventNotInitialized = "Logger controller boss selection event is not initialized"
Diag.A.LoggerControllerDataChangedEventNotInitialized = "Logger controller data-changed event is not initialized"
Diag.A.LoggerControllerEventListenerNotInitialized = "Logger controller event listener is not initialized"
Diag.A.LoggerControllerEventPublisherNotInitialized = "Logger controller event publisher is not initialized"
Diag.A.LoggerControllerInternalEventsNotInitialized = "Logger controller internal events are not initialized"
Diag.A.LoggerControllerItemSelectionEventNotInitialized = "Logger controller item selection event is not initialized"
Diag.A.LoggerControllerLootChangedEventNotInitialized = "Logger controller loot-changed event is not initialized"
Diag.A.LoggerControllerPlayerSelectionClearEventNotInitialized = "Logger controller player selection-clear event is not initialized"
Diag.A.LoggerControllerPlayerSelectionEventNotInitialized = "Logger controller player selection event is not initialized"
Diag.A.LoggerControllerRaidCreateEventNotInitialized = "Logger controller raid-create event is not initialized"
Diag.A.LoggerControllerRaidLootUpdateEventNotInitialized = "Logger controller raid loot update event is not initialized"
Diag.A.LoggerControllerRaidOfferEventNotInitialized = "Logger controller raid-offer event is not initialized"
Diag.A.LoggerControllerRaidReEntryDecisionRequiredEventNotInitialized = "Logger controller raid re-entry decision-required event is not initialized"
Diag.A.LoggerControllerRaidReEntryDecisionResolvedEventNotInitialized = "Logger controller raid re-entry decision-resolved event is not initialized"
Diag.A.LoggerControllerRaidSelectionEventNotInitialized = "Logger controller raid selection event is not initialized"
Diag.A.LoggerControllerRosterDeltaEventNotInitialized = "Logger controller roster-delta event is not initialized"
Diag.A.LoggerDropdownAddButtonApiNotInitialized = "Logger dropdown add-button API is not initialized"
Diag.A.LoggerDropdownButtonWidthApiNotInitialized = "Logger dropdown button-width API is not initialized"
Diag.A.LoggerDropdownInfoApiNotInitialized = "Logger dropdown info API is not initialized"
Diag.A.LoggerDropdownInitApiNotInitialized = "Logger dropdown init API is not initialized"
Diag.A.LoggerDropdownTextApiNotInitialized = "Logger dropdown text API is not initialized"
Diag.A.LoggerDropdownWidthApiNotInitialized = "Logger dropdown width API is not initialized"
Diag.A.LoggerEditBoxPopupShowerNotInitialized = "Logger edit-box popup shower is not initialized"
Diag.A.LoggerExportDialogOwnerNotInitialized = "Logger export dialog owner is not initialized"
Diag.A.LoggerExportServiceNotInitialized = "Logger export service is not initialized"
Diag.A.LoggerFrameCreationApiNotInitialized = "Logger frame creation API is not initialized"
Diag.A.LoggerFrameGetterFactoryNotInitialized = "Logger frame getter factory is not initialized"
Diag.A.LoggerFrameRefResolverNotInitialized = "Logger frame ref resolver is not initialized"
Diag.A.LoggerFrameScriptBinderNotInitialized = "Logger frame script binder is not initialized"
Diag.A.LoggerFrameTitleBinderNotInitialized = "Logger frame title binder is not initialized"
Diag.A.LoggerGroupHelperOwnerNotInitialized = "Logger group helper owner is not initialized"
Diag.A.LoggerHelperServiceNotInitialized = "Logger helper service is not initialized"
Diag.A.LoggerItemIconApiNotInitialized = "Logger item icon API is not initialized"
Diag.A.LoggerItemTooltipRendererNotInitialized = "Logger item tooltip renderer is not initialized"
Diag.A.LoggerModuleFrameBinderNotInitialized = "Logger module frame binder is not initialized"
Diag.A.LoggerModuleFrameGetterFactoryNotInitialized = "Logger module frame getter factory is not initialized"
Diag.A.LoggerPopupDefinedStateCheckerNotInitialized = "Logger popup defined-state checker is not initialized"
Diag.A.LoggerPopupDefinerNotInitialized = "Logger popup definer is not initialized"
Diag.A.LoggerPopupHiderNotInitialized = "Logger popup hider is not initialized"
Diag.A.LoggerPopupNamespaceNotInitialized = "Logger popup namespace is not initialized"
Diag.A.LoggerPopupResizerNotInitialized = "Logger popup resizer is not initialized"
Diag.A.LoggerPopupShowerNotInitialized = "Logger popup shower is not initialized"
Diag.A.LoggerRaidProjectionsServiceNotInitialized = "Logger raid projections service is not initialized"
Diag.A.LoggerRaidServiceNotInitialized = "Logger raid service is not initialized"
Diag.A.LoggerRootUiParentNotInitialized = "Logger root UI parent is not initialized"
Diag.A.LoggerServiceNamespaceNotInitialized = "Logger service namespace is not initialized"
Diag.A.LoggerSourceTooltipModelBinderNotInitialized = "Logger source tooltip model binder is not initialized"
Diag.A.LoggerStoreServiceNotInitialized = "Logger store service is not initialized"
Diag.A.LoggerTooltipBinderNotInitialized = "Logger tooltip binder is not initialized"
Diag.A.LoggerTooltipHideServiceNotInitialized = "Logger tooltip hide service is not initialized"
Diag.A.LoggerTooltipLineRendererNotInitialized = "Logger tooltip line renderer is not initialized"
Diag.A.LoggerUnitIdentityApiNotInitialized = "Logger unit-identity API is not initialized"
Diag.A.LoggerUnitNameApiNotInitialized = "Logger unit-name API is not initialized"
Diag.A.LoggerViewServiceNotInitialized = "Logger view service is not initialized"
Diag.A.MasterAssignmentServiceNotInitialized = "Master assignment service is not initialized"
Diag.A.MasterAwardSequenceServiceNotInitialized = "Master award sequence service is not initialized"
Diag.A.MasterChatServiceNotInitialized = "Master chat service is not initialized"
Diag.A.MasterConfirmPopupShowerNotInitialized = "Master confirm popup shower is not initialized"
Diag.A.MasterControllerAddRollEventNotInitialized = "Master controller add-roll event is not initialized"
Diag.A.MasterControllerDropdownButtonApiNotInitialized = "Master controller dropdown button API is not initialized"
Diag.A.MasterControllerDropdownButtonWidthApiNotInitialized = "Master controller dropdown button-width API is not initialized"
Diag.A.MasterControllerDropdownInfoApiNotInitialized = "Master controller dropdown info API is not initialized"
Diag.A.MasterControllerDropdownInitApiNotInitialized = "Master controller dropdown init API is not initialized"
Diag.A.MasterControllerDropdownJustifyApiNotInitialized = "Master controller dropdown justify API is not initialized"
Diag.A.MasterControllerDropdownSelectedValueApiNotInitialized = "Master controller dropdown selected-value API is not initialized"
Diag.A.MasterControllerDropdownTextApiNotInitialized = "Master controller dropdown text API is not initialized"
Diag.A.MasterControllerDropdownWidthApiNotInitialized = "Master controller dropdown width API is not initialized"
Diag.A.MasterControllerEventListenerNotInitialized = "Master controller event listener is not initialized"
Diag.A.MasterControllerEventPublisherNotInitialized = "Master controller event publisher is not initialized"
Diag.A.MasterControllerForwardedEventResolverNotInitialized = "Master controller forwarded-event resolver is not initialized"
Diag.A.MasterControllerFrameCreationApiNotInitialized = "Master controller frame creation API is not initialized"
Diag.A.MasterControllerGroupLootRestorePromptEventNotInitialized = "Master controller group-loot restore prompt event is not initialized"
Diag.A.MasterControllerInternalEventsNotInitialized = "Master controller internal events are not initialized"
Diag.A.MasterControllerLootAssignmentApiNotInitialized = "Master controller loot assignment API is not initialized"
Diag.A.MasterControllerLootBansChangedEventNotInitialized = "Master controller loot bans changed event is not initialized"
Diag.A.MasterControllerLootCandidateApiNotInitialized = "Master controller loot candidate API is not initialized"
Diag.A.MasterControllerLootCounterSettingEventNotInitialized = "Master controller loot-counter setting event is not initialized"
Diag.A.MasterControllerLootSlotInfoApiNotInitialized = "Master controller loot slot info API is not initialized"
Diag.A.MasterControllerRaidRosterApiNotInitialized = "Master controller raid roster API is not initialized"
Diag.A.MasterControllerRaidRosterDeltaEventNotInitialized = "Master controller raid roster delta event is not initialized"
Diag.A.MasterControllerReservesDataChangedEventNotInitialized = "Master controller reserves data changed event is not initialized"
Diag.A.MasterControllerSetItemEventNotInitialized = "Master controller set-item event is not initialized"
Diag.A.MasterControllerSortSettingEventNotInitialized = "Master controller sort setting event is not initialized"
Diag.A.MasterControllerSpecInspectUpdateEventNotInitialized = "Master controller spec inspect update event is not initialized"
Diag.A.MasterControllerUnitNameApiNotInitialized = "Master controller unit name API is not initialized"
Diag.A.MasterDebugEntrypointNotInitialized = "Master debug entrypoint is not initialized"
Diag.A.MasterFrameRefResolverNotInitialized = "Master frame ref resolver is not initialized"
Diag.A.MasterFrameScriptBinderNotInitialized = "Master frame script binder is not initialized"
Diag.A.MasterFrameTitleBinderNotInitialized = "Master frame title binder is not initialized"
Diag.A.MasterIndexedRowNameFactoryNotInitialized = "Master indexed row-name factory is not initialized"
Diag.A.MasterItemSelectionWidgetNotInitialized = "Master item selection widget is not initialized"
Diag.A.MasterListControllerNamespaceNotInitialized = "Master list controller namespace is not initialized"
Diag.A.MasterLoggerActionsServiceNotInitialized = "Master logger actions service is not initialized"
Diag.A.MasterLootBansServiceNotInitialized = "Master loot bans service is not initialized"
Diag.A.MasterLootDistributionOwnerNotInitialized = "Master loot distribution owner is not initialized"
Diag.A.MasterLootServiceNotInitialized = "Master loot service is not initialized"
Diag.A.MasterModuleFrameBinderNotInitialized = "Master module frame binder is not initialized"
Diag.A.MasterModuleFrameGetterFactoryNotInitialized = "Master module frame getter factory is not initialized"
Diag.A.MasterPopupDefinedStateCheckerNotInitialized = "Master popup defined-state checker is not initialized"
Diag.A.MasterPopupDefinerNotInitialized = "Master popup definer is not initialized"
Diag.A.MasterPopupNamespaceNotInitialized = "Master popup namespace is not initialized"
Diag.A.MasterPopupShowerNotInitialized = "Master popup shower is not initialized"
Diag.A.MasterRaidServiceNotInitialized = "Master raid service is not initialized"
Diag.A.MasterRollListControllerFactoryNotInitialized = "Master roll list controller factory is not initialized"
Diag.A.MasterRollRowRendererFactoryNotInitialized = "Master roll row renderer factory is not initialized"
Diag.A.MasterRollSelectionServiceNotInitialized = "Master Roll Selection service is not initialized"
Diag.A.MasterRollsServiceNotInitialized = "Master rolls service is not initialized"
Diag.A.MasterTooltipBinderNotInitialized = "Master tooltip binder is not initialized"
Diag.A.MasterTooltipHiderNotInitialized = "Master tooltip hider is not initialized"
Diag.A.MasterTradeExecutionServiceNotInitialized = "Master trade execution service is not initialized"
Diag.A.RaidDebugServiceNotInitialized = "Raid debug service is not initialized"
Diag.A.SpammerControllerChatServiceNotInitialized = "Spammer controller chat service is not initialized"
Diag.A.SpammerControllerDraftServiceNotInitialized = "Spammer controller draft service is not initialized"
Diag.A.SpammerControllerRuntimeServiceNotInitialized = "Spammer controller runtime service is not initialized"
Diag.A.SpammerControllerServiceNamespaceNotInitialized = "Spammer controller service namespace is not initialized"
Diag.A.WarningsControllerChatServiceNotInitialized = "Warnings controller chat service is not initialized"
Diag.A.WarningsControllerDataChangedEventNotInitialized = "Warnings controller data-changed event is not initialized"
Diag.A.WarningsControllerEventListenerNotInitialized = "Warnings controller event listener is not initialized"
Diag.A.WarningsControllerInternalEventsNotInitialized = "Warnings controller internal events are not initialized"
Diag.A.WarningsControllerServiceNamespaceNotInitialized = "Warnings controller service namespace is not initialized"
Diag.A.WarningsControllerStoreServiceNotInitialized = "Warnings controller store service is not initialized"

-- Widgets --
Diag.A.LootCounterChatAnnouncementServiceNotInitialized = "LootCounter chat announcement service is not initialized"
Diag.A.LootCounterChatServiceNotInitialized = "LootCounter chat service is not initialized"
Diag.A.LootCounterCountChangedEventNotInitialized = "LootCounter count-changed event is not initialized"
Diag.A.LootCounterEventBusListenerNotInitialized = "LootCounter event bus listener is not initialized"
Diag.A.LootCounterInternalEventsNotInitialized = "LootCounter internal events are not initialized"
Diag.A.LootCounterPopupConfirmationBuilderNotInitialized = "LootCounter popup confirmation builder is not initialized"
Diag.A.LootCounterPopupDisplayServiceNotInitialized = "LootCounter popup display service is not initialized"
Diag.A.LootCounterPopupRegistryNotInitialized = "LootCounter popup registry is not initialized"
Diag.A.LootCounterRaidCapabilityServiceNotInitialized = "LootCounter raid capability service is not initialized"
Diag.A.LootCounterRaidClassResolverNotInitialized = "LootCounter raid class resolver is not initialized"
Diag.A.LootCounterRaidCountIncrementServiceNotInitialized = "LootCounter raid count increment service is not initialized"
Diag.A.LootCounterRaidCountRowServiceNotInitialized = "LootCounter raid count row service is not initialized"
Diag.A.LootCounterRaidCountSetterServiceNotInitialized = "LootCounter raid count setter service is not initialized"
Diag.A.LootCounterRaidCreateEventNotInitialized = "LootCounter raid-create event is not initialized"
Diag.A.LootCounterRaidMembershipServiceNotInitialized = "LootCounter raid membership service is not initialized"
Diag.A.LootCounterRaidServiceNotInitialized = "LootCounter raid service is not initialized"
Diag.A.LootCounterRosterDeltaEventNotInitialized = "LootCounter roster-delta event is not initialized"
Diag.A.LootCounterSpecInspectServiceNotInitialized = "LootCounter spec inspect service is not initialized"
Diag.A.LootCounterSpecSnapshotResolverNotInitialized = "LootCounter spec snapshot resolver is not initialized"
Diag.A.LootCounterSpecUpdateEventNotInitialized = "LootCounter spec update event is not initialized"
Diag.A.LootCounterTextureColorPrimitiveNotInitialized = "LootCounter texture-color primitive is not initialized"
Diag.A.LootHintsFrameHookBinderNotInitialized = "Loot hints frame hook binder is not initialized"
Diag.A.LootHintsFrameScriptBinderNotInitialized = "Loot hints frame script binder is not initialized"
Diag.A.LootHintsItemTooltipPresenterNotInitialized = "Loot hints item tooltip presenter is not initialized"
Diag.A.LootHintsLootFrameUpdateApiNotInitialized = "Loot hints loot-frame update API is not initialized"
Diag.A.LootHintsReservePlayerLookupNotInitialized = "Loot hints reserve player lookup is not initialized"
Diag.A.LootHintsReserveStateResolverNotInitialized = "Loot hints reserve-state resolver is not initialized"
Diag.A.LootHintsReservesServiceNotInitialized = "Loot hints reserves service is not initialized"
Diag.A.LootHintsSecureHookApiNotInitialized = "Loot hints secure hook API is not initialized"
Diag.A.LootHintsTooltipHiderNotInitialized = "Loot hints tooltip hider is not initialized"
Diag.A.MasterItemSelectionAnchorButtonResolverNotInitialized = "Master item selection anchor-button resolver is not initialized"
Diag.A.MasterItemSelectionAnnounceStateSetterNotInitialized = "Master item selection announce-state setter is not initialized"
Diag.A.MasterItemSelectionCountdownStateResolverNotInitialized = "Master item selection countdown-state resolver is not initialized"
Diag.A.MasterItemSelectionFrameFactoryNotInitialized = "Master item selection frame factory is not initialized"
Diag.A.MasterItemSelectionFrameNameResolverNotInitialized = "Master item selection frame-name resolver is not initialized"
Diag.A.MasterItemSelectionFrameResolverNotInitialized = "Master item selection frame resolver is not initialized"
Diag.A.MasterItemSelectionInventoryOwnerNotInitialized = "Master item selection inventory owner is not initialized"
Diag.A.MasterItemSelectionItemCountResetterNotInitialized = "Master item selection item-count resetter is not initialized"
Diag.A.MasterItemSelectionItemStateNotInitialized = "Master item selection item state is not initialized"
Diag.A.MasterItemSelectionLocalizedStringsNotInitialized = "Master item selection localized strings are not initialized"
Diag.A.MasterItemSelectionLootItemAdderNotInitialized = "Master item selection loot-item adder is not initialized"
Diag.A.MasterItemSelectionLootItemNameResolverNotInitialized = "Master item selection loot-item-name resolver is not initialized"
Diag.A.MasterItemSelectionLootItemPreparerNotInitialized = "Master item selection loot-item preparer is not initialized"
Diag.A.MasterItemSelectionLootItemResolverNotInitialized = "Master item selection loot-item resolver is not initialized"
Diag.A.MasterItemSelectionLootItemTextureResolverNotInitialized = "Master item selection loot-item-texture resolver is not initialized"
Diag.A.MasterItemSelectionLootStateNotInitialized = "Master item selection loot state is not initialized"
Diag.A.MasterItemSelectionNamedPartsResolverNotInitialized = "Master item selection named-parts resolver is not initialized"
Diag.A.MasterItemSelectionPostApplyCallbackNotInitialized = "Master item selection post-apply callback is not initialized"
Diag.A.MasterItemSelectionRowSelectionCallbackNotInitialized = "Master item selection row-selection callback is not initialized"
Diag.A.MasterItemSelectionScriptBinderNotInitialized = "Master item selection script binder is not initialized"
Diag.A.MasterItemSelectionStateNotInitialized = "Master item selection state is not initialized"
Diag.A.MasterItemSelectionWoWApiTableNotInitialized = "Master item selection WoW API table is not initialized"
Diag.A.QuickBarLoggerControllerNotInitialized = "QuickBar logger controller is not initialized"
Diag.A.QuickBarForwardedRaidRosterEventNotInitialized = "QuickBar forwarded raid-roster event is not initialized"
Diag.A.QuickBarLootMethodEventNotInitialized = "QuickBar loot-method event is not initialized"
Diag.A.QuickBarRaidMembershipResolverNotInitialized = "QuickBar raid-membership resolver is not initialized"
Diag.A.QuickBarRaidRosterEventNotInitialized = "QuickBar raid-roster event is not initialized"
Diag.A.QuickBarRaidServiceNotInitialized = "QuickBar raid service is not initialized"
Diag.A.QuickBarReservesWidgetNotInitialized = "QuickBar reserves widget is not initialized"
Diag.A.QuickBarWarningsControllerNotInitialized = "QuickBar warnings controller is not initialized"
Diag.A.RaidGridButtonCreationApiNotInitialized = "RaidGrid button creation API is not initialized"
Diag.A.RaidGridEventBusListenerNotInitialized = "RaidGrid event bus listener is not initialized"
Diag.A.RaidGridFrameTitleServiceNotInitialized = "RaidGrid frame title service is not initialized"
Diag.A.RaidGridInternalEventsNotInitialized = "RaidGrid internal events are not initialized"
Diag.A.RaidGridSpecInspectServiceNotInitialized = "RaidGrid spec inspect service is not initialized"
Diag.A.RaidGridSpecSnapshotResolverNotInitialized = "RaidGrid spec snapshot resolver is not initialized"
Diag.A.RaidGridSpecUpdateEventNotInitialized = "RaidGrid spec update event is not initialized"
Diag.A.RaidGridTextureColorPrimitiveNotInitialized = "RaidGrid texture-color primitive is not initialized"
Diag.A.RaidGridTooltipDisplayServiceNotInitialized = "RaidGrid tooltip display service is not initialized"
Diag.A.RaidGridTooltipHideServiceNotInitialized = "RaidGrid tooltip hide service is not initialized"
Diag.A.ReservesUiBatchEditorNotInitialized = "Reserves UI batch editor is not initialized"
Diag.A.ReservesUiChatAnnouncerNotInitialized = "Reserves UI chat announcer is not initialized"
Diag.A.ReservesUiChatServiceNotInitialized = "Reserves UI chat service is not initialized"
Diag.A.ReservesUiClassColorResolverNotInitialized = "Reserves UI class-color resolver is not initialized"
Diag.A.ReservesUiClearSavedHandlerNotInitialized = "Reserves UI clear-saved handler is not initialized"
Diag.A.ReservesUiConfirmPopupDefinerNotInitialized = "Reserves UI confirm popup definer is not initialized"
Diag.A.ReservesUiConfirmPopupShowerNotInitialized = "Reserves UI confirm popup shower is not initialized"
Diag.A.ReservesUiDataChangedEventNotInitialized = "Reserves UI data-changed event is not initialized"
Diag.A.ReservesUiDataStateResolverNotInitialized = "Reserves UI data-state resolver is not initialized"
Diag.A.ReservesUiDisplayListResolverNotInitialized = "Reserves UI display-list resolver is not initialized"
Diag.A.ReservesUiEventBusListenerNotInitialized = "Reserves UI event bus listener is not initialized"
Diag.A.ReservesUiImportApplyHandlerNotInitialized = "Reserves UI import-apply handler is not initialized"
Diag.A.ReservesUiImportModeGetterNotInitialized = "Reserves UI import-mode getter is not initialized"
Diag.A.ReservesUiImportModeResolverNotInitialized = "Reserves UI import-mode resolver is not initialized"
Diag.A.ReservesUiImportModeSetterNotInitialized = "Reserves UI import-mode setter is not initialized"
Diag.A.ReservesUiImportParserNotInitialized = "Reserves UI import parser is not initialized"
Diag.A.ReservesUiInternalEventsNotInitialized = "Reserves UI internal events are not initialized"
Diag.A.ReservesUiItemTooltipPresenterNotInitialized = "Reserves UI item tooltip presenter is not initialized"
Diag.A.ReservesUiOptionsNamespaceResolverNotInitialized = "Reserves UI options namespace resolver is not initialized"
Diag.A.ReservesUiPendingItemResolverNotInitialized = "Reserves UI pending-item resolver is not initialized"
Diag.A.ReservesUiPopupDefinedStateCheckerNotInitialized = "Reserves UI popup defined-state checker is not initialized"
Diag.A.ReservesUiPopupDefinerNotInitialized = "Reserves UI popup definer is not initialized"
Diag.A.ReservesUiPopupNamespaceNotInitialized = "Reserves UI popup namespace is not initialized"
Diag.A.ReservesUiPopupShowerNotInitialized = "Reserves UI popup shower is not initialized"
Diag.A.ReservesUiRaidClassResolverNotInitialized = "Reserves UI raid class resolver is not initialized"
Diag.A.ReservesUiRaidMemberCountApiNotInitialized = "Reserves UI raid member count API is not initialized"
Diag.A.ReservesUiRaidServiceNotInitialized = "Reserves UI raid service is not initialized"
Diag.A.ReservesUiRemoveReserveHandlerNotInitialized = "Reserves UI remove-reserve handler is not initialized"
Diag.A.ReservesUiServiceNotInitialized = "Reserves UI service is not initialized"
Diag.A.ReservesUiTimeApiNotInitialized = "Reserves UI time API is not initialized"
Diag.A.ReservesUiTooltipBinderNotInitialized = "Reserves UI tooltip binder is not initialized"
Diag.A.ReservesUiTooltipHiderNotInitialized = "Reserves UI tooltip hider is not initialized"
Diag.A.ReservesUiUnitNameApiNotInitialized = "Reserves UI unit name API is not initialized"
Diag.A.TradeMenuFrameCreationApiNotInitialized = "Trade menu frame creation API is not initialized"
Diag.A.TradeMenuItemLinkApiNotInitialized = "Trade menu item link API is not initialized"
Diag.A.TradeMenuRootUiParentNotInitialized = "Trade menu root UI parent is not initialized"
Diag.A.TradeMenuUnitNameApiNotInitialized = "Trade menu unit name API is not initialized"

-- ----- Internal state ----- --

-- ----- Private helpers ----- --

-- ----- Public methods ----- --

-- ==================== Log Messages ==================== --
-- Database --
Diag.I.LogDatabaseLoaded = "[Database] Loaded version=%s logLevel=%s perfMode=%s"
Diag.D.LogDatabaseEventsRegistered = "[Database] Events registered=%d"
Diag.D.LogDatabasePlayerEnteringWorld = "[Database] PLAYER_ENTERING_WORLD -> scheduling CheckInitialRaidState"
Diag.E.LogDatabaseEventHandlerFailed = "[Database] Event handler failed event=%s err=%s"
Diag.I.LogPerfBlock = "[Perf] %s %.1fms%s"

-- Utils --
Diag.E.LogUtilsCallbackExec = "Error while executing callback %s for event %s: %s"
Diag.D.LogListHighlightRefresh = "[%s] refresh key=%s%s"

-- Raid --
Diag.D.LogRaidLeftGroupEndSession = "[Raid] Left group -> ending current raid session"
Diag.D.LogRaidRosterUpdate = "[Raid] RosterUpdate v=%d num=%d"
Diag.I.LogRaidCreated = "[Raid] Created id=%d zone=%s size=%d players=%d"
Diag.I.LogRaidEnded = "[Raid] Ended id=%d zone=%s size=%d bosses=%d loot=%d duration=%d"
Diag.D.LogRaidCheck = "[Raid] Check zone=%s diff=%s current=%s"
Diag.D.LogRaidSessionChange = "[Raid] Session change zone=%s size=%d diff=%d"
Diag.D.LogRaidSessionCreate = "[Raid] Session create zone=%s size=%d diff=%d"
Diag.D.LogRaidCheckInitialRaidState =
	"[Raid] CheckInitialRaidState inGroup=%s currentRaid=%s instance=%s type=%s diff=%s"
Diag.D.LogRaidPlayerJoin = "[Raid] Player join name=%s raidId=%d"
Diag.D.LogRaidPlayerRefresh = "[Raid] Player refresh name=%s raidId=%d"
Diag.D.LogRaidInstanceWelcome = "[Raid] RAID_INSTANCE_WELCOME name=%s type=%s diff=%s nextReset=%s"
Diag.W.LogRaidUnmappedZone = "[Raid] Unmapped raid zone: %s (diff=%s) -> no session check"
Diag.D.LogRaidInstanceRecognized = "[Raid] Instance recognized: %s diff=%s -> check"
Diag.D.LogRaidReentryRecovery = "[Raid] Reentry recovery phase=%s reason=%s"
Diag.D.LogDebugRaidSeed = "[Debug] Raid seed raidId=%s name=%s class=%s"
Diag.D.LogDebugRaidClearRemoved = "[Debug] Raid clear removed raidId=%s name=%s nid=%s"
Diag.D.LogDebugRaidClearBlocked = "[Debug] Raid clear blocked raidId=%s name=%s nid=%s"
Diag.D.LogDebugRaidRoll = "[Debug] Raid roll raidId=%s name=%s roll=%d ok=%s reason=%s"

-- Boss --
Diag.D.LogBossAddSkipped = "[Boss] AddBoss skipped raidId=%s boss=%s"
Diag.I.LogBossLogged = "[Boss] Logged boss=%s diff=%d raid=%d players=%d"
Diag.D.LogBossLastBossHash = "[Boss] lastBoss=%d hash=%s"
Diag.D.LogBossNoContextTrash = "[Boss] No boss context -> creating _TrashMob_ bucket"
Diag.D.LogBossEventContextSet = "[Boss] Event context set boss=%s bossNid=%d raid=%d source=%s"
Diag.D.LogBossEventContextRecovered = "[Boss] Event context recovered boss=%s bossNid=%d delta=%d source=%s"
Diag.D.LogBossLootWindowContextSet = "[Boss] Loot-window context set boss=%s bossNid=%d raid=%d source=%s"
Diag.D.LogBossLootWindowContextRecovered = "[Boss] Loot-window context recovered boss=%s bossNid=%d raid=%d source=%s"
Diag.D.LogBossLootWindowContextBlocked = "[Boss] Loot-window context blocked raid=%d unit=%s name=%s npcId=%d source=%s"
Diag.D.LogBossYellMatched = "[Boss] Yell matched text=%s boss=%s"
Diag.D.LogBossUnitDiedMatched = "[Boss] UNIT_DIED matched npcId=%d boss=%s"
Diag.D.LogBossUnitDiedIgnored = "[Boss] UNIT_DIED ignored npcId=%d boss=%s"
Diag.D.LogBossDuplicateSuppressed = "[Boss] Duplicate suppressed boss=%s sourceNpcId=%d existingBossNid=%d delta=%d"
Diag.D.LogLootSourceResolved = "[LootSource] Resolved itemId=%s raid=%s source=%s npcId=%d kind=%s confidence=%s"
Diag.D.LogLootSourceMissing = "[LootSource] Missing itemId=%s raid=%s"
Diag.D.LogLootSourceAmbiguous = "[LootSource] Ambiguous itemId=%s raid=%s candidates=%d"

-- Master --
Diag.E.LogMasterUILocalizationFailed = "[Master] UI localization failed; controls are still bound."

-- Loot --
Diag.D.LogLootParseFailed = "[Loot] Parse failed msg=%s"
Diag.D.LogLootParsed = "[Loot] Parsed looter=%s link=%s count=%d"
Diag.D.LogLootTaggedManual = "[Loot] tagged MANUAL (no matching pending award) item=%s -> %s (lastRollType=%s)."
Diag.D.LogLootIgnoredBelowThreshold = "[Loot] Ignored below threshold rarity=%s thr=%d link=%s"
Diag.D.LogLootIgnoredItemId = "[Loot] Ignored itemId=%s link=%s (ignoredItems)"
Diag.D.LogLootLogged = "[Loot] Logged raidId=%d itemId=%s bossNid=%s looter=%s"
Diag.D.LogLootFetchStart = "[Loot] FetchLoot numLootItems=%d oldIndex=%d"
Diag.D.LogLootFetchDone = "[Loot] FetchLoot done lootCount=%d currentIndex=%d"
Diag.D.LogLootItemInfoMissing = "[Loot] ItemInfo missing -> deferred link=%s"
Diag.D.LogLootChatMsgLootRaw = "[Loot] CHAT_MSG_LOOT raw=%s"
Diag.D.LogLootGroupSelectionQueued = "[Loot] Group selection queued type=%s looter=%s link=%s"
Diag.D.LogLootGroupWinnerDetected = "[Loot] Group winner observed looter=%s msgType=%s msgRoll=%s link=%s"
Diag.D.LogLootPendingAwardConsumed = "[Loot] Pending consumed item=%s looter=%s remaining=%d ttl=%d"
Diag.D.LogLootTradeOnlyLogged = "[Loot] Trade-only logged raidId=%d itemId=%s lootNid=%s looter=%s count=%d source=%s"
Diag.D.LogDistributionSnapshotSent = "[Loot] Distribution snapshot sent rows=%d target=%s"
Diag.D.LogDistributionSnapshotApplied = "[Loot] Distribution snapshot applied rows=%d sender=%s"
Diag.W.LogDistributionUnsupportedVersion = "[Loot] Distribution message ignored unsupported version=%s"

-- MasterLooter --
Diag.D.LogMLCandidateCacheBuilt = "[ML] Candidate cache built item=%s candidates=%d"
Diag.D.LogMLAwardRequested = "[ML] Award requested winner=%s type=%d roll=%d item=%s"
Diag.W.LogMLCountdownActive = "[ML] Countdown active: wait for it to finish before awarding"
Diag.D.LogMLAwardBlocked = "[ML] Award blocked lootCount=%d rollsCount=%d"
Diag.D.LogMLInventorySoulbound = "[ML] Inventory item is soulbound -> cannot trade link=%s"
Diag.D.LogMLLootOpenedTrace = "[ML] LOOT_OPENED items=%d fromInv=%s"
Diag.D.LogMLLootOpenedInfo = "[ML] Loot opened items=%d fromInv=%s target=%s"
Diag.D.LogMLLootClosed = "[ML] LOOT_CLOSED opened=%s items=%d"
Diag.D.LogMLLootClosedCleanup = "[ML] LOOT_CLOSED -> scheduling cleanup"
Diag.D.LogMLLootSlotCleared = "[ML] LOOT_SLOT_CLEARED items=%d"
Diag.D.LogMLLootWindowEmptied = "[ML] Loot window emptied"
Diag.D.LogMLCandidateCacheMiss = "[ML] Candidate cache miss item=%s player=%s -> rebuild"
Diag.D.LogMLAwarded = "[ML] Awarded item=%s -> %s type=%d roll=%d slot=%d cand=%d"
Diag.W.LogMLAwardConfirmationFailed = "[ML] Pending award execution cancelled item=%s player=%s reason=%s"
Diag.W.LogMLAwardConfirmationTimeout = "[ML] Pending award execution unconfirmed after %ds item=%s player=%s slot=%s"
Diag.W.LogMLSetItemPayloadInvalid = "[ML] SetItem payload invalid itemLink=%s itemDataType=%s"
Diag.W.LogMLRaidRosterDeltaPayloadInvalid = "[ML] RaidRosterDelta payload invalid deltaType=%s "
	.. "rosterVersion=%s raidId=%s"
Diag.W.LogMLAddRollPayloadInvalid = "[ML] AddRoll payload invalid name=%s roll=%s"
Diag.W.ErrMLMultiAwardInProgress = "[ML] Multi-award in progress: wait until it finishes before awarding again."
Diag.W.ErrMLMultiSelectTooMany = "[ML] Cannot select more than %d winner(s) for this item."
Diag.W.ErrMLMultiSelectNotEnough = "[ML] Select %d winner(s) before awarding multiple copies (currently %d)."
Diag.D.LogMLMultiAwardStarted = "[ML] Multi-award start item=%s total=%d available=%d slots=%s timeout=%ds"
Diag.I.LogMLTieReroll = "[ML] Tie reroll item=%s players=%s"
Diag.W.ErrMLMultiAwardInterruptedTimeout = "[ML] Multi-award interrupted: loot window did not update as expected within %ds "
	.. "item=%s expected<%d observed=%d slot=%s"

-- Trade --
Diag.D.LogTradeAcceptUpdate = "[Trade] ACCEPT_UPDATE trader=%s winner=%s t=%s p=%s"
Diag.D.LogTradeCompleted = "[Trade] Completed item=%s winner=%s type=%d roll=%d"
Diag.W.LogTradeCurrentRollItemMissing = "[Trade] currentRollItem missing; cannot update loot entry"
Diag.W.LogTradeCurrentRollItemMissingContext = "[Trade] currentRollItem missing winner=%s itemId=%s link=%s"
Diag.E.LogTradeLoggerLogFailed = "[Trade] Logger log failed raidId=%s lootNid=%s link=%s"
Diag.E.LogTradeKeepLoggerFailed = "[Trade] Keep logged but Logger failed raidId=%s lootNid=%s link=%s"
Diag.D.LogTradeStart = "[Trade] TradeItem start item=%s trader=%s target=%s type=%d roll=%d count=%d"
Diag.D.LogTradeTraderKeeps = "[Trade] Trader keeps item=%s winner=%s"
Diag.D.LogTradeAwardedCountResolved = "[Trade] Awarded count=%d source=%s before=%s after=%s selected=%d"
Diag.D.LogTradeStackBlocked = "[Trade] Stack trade blocked ignoreStacks=%s link=%s"
Diag.D.LogTradeInitiated = "[Trade] Initiated item=%s -> %s"
Diag.W.LogTradeDelayedOutOfRange = "[Trade] Delayed: %s out of range item=%s"
Diag.W.LogTradeNoLootContextTradeOnly =
	"[Trade] No lootNid context; created trade-only entry lootNid=%s winner=%s item=%s count=%d"
Diag.D.LogManualTradeCandidateFound = "[Trade] Manual candidate found partner=%s count=%d lootNid=%s"
Diag.D.LogManualTradeLogged = "[Trade] Manual trade logged lootNid=%s partner=%s reason=%s"
Diag.W.LogManualTradeNoPartner = "[Trade] Manual trade skipped: no trade partner resolved for source=%s"
Diag.W.LogManualTradeNoCurrentRaid = "[Trade] Manual trade skipped: no current raid"
Diag.W.LogManualTradeNoTradeItems = "[Trade] Manual trade skipped: no player-side trade items available"
Diag.W.LogManualTradeNoLocalHold = "[Trade] Manual trade skipped: no local HOLD loot found in current raid"
Diag.W.LogManualTradeNoMatch = "[Trade] Manual trade candidate scan found no HOLD matches for partner=%s raid=%s"
Diag.W.LogManualTradeMissingReason = "[Trade] Manual trade slot %s skipped: no reason selected"

-- SoftRes --
Diag.D.LogSRImportRequested = "[SR] Import requested chars=%d"
Diag.D.LogSRParseSkippedLine = "[SR] ParseCSV skipped line=%s"
Diag.D.LogSRQueryMissingItems = "[SR] QueryMissingItems updated=%s pending=%d"

-- Rolls --
Diag.D.LogRollsAddEntry = "[Rolls] Add name=%s roll=%d item=%s"
Diag.D.LogRollsBlockedPlayer = "[Rolls] Blocked player=%s (%d/%d)"
Diag.D.LogRollsPlayerRolled = "[Rolls] Player=%s item=%d"
Diag.D.LogRollsRecordState = "[Rolls] Record=%s"
Diag.W.LogRollsMissingItem = "[Rolls] Item ID missing or loot table not ready - roll ignored"
Diag.D.LogRollsDeniedPlayer = "[Rolls] Denied player=%s (%d/%d)"
Diag.D.LogRollsAcceptedPlayer = "[Rolls] Accepted player=%s (%d/%d)"
Diag.D.LogRollsCurrentItemId = "[Rolls] Current itemId=%s"
Diag.D.LogRollsEligibility = "[Rolls] Eligibility name=%s ok=%s bucket=%s reason=%s used=%d/%d"
Diag.D.LogRollsResponse = "[Rolls] Response name=%s status=%s bucket=%s best=%s last=%s"
Diag.D.LogRollsResolution = "[Rolls] Resolution top=%s tied=%s cutoff=%d manual=%s"
Diag.D.LogRollsTimedOut = "[Rolls] Timed out name=%s"
Diag.D.LogRollsTieReroll = "[Rolls] Tie reroll item=%s players=%s"

-- Reserves --
Diag.D.LogReservesTrackPending = "[Reserves] Track pending itemId=%d pending=%d"
Diag.D.LogReservesItemReady = "[Reserves] Item ready itemId=%d pending=%d"
Diag.D.LogReservesPendingComplete = "[Reserves] Pending item info complete"
Diag.D.LogReservesToggleCollapse = "[Reserves] Toggle collapse source=%s state=%s"
Diag.D.LogReservesSaveEntries = "[Reserves] Save entries=%d"
Diag.D.LogReservesLoadData = "[Reserves] Load data=%s"
Diag.D.LogReservesClearSavedReserves = "[Reserves] Reset saved data"
Diag.D.LogReservesShowWindow = "[Reserves] Show list window"
Diag.D.LogReservesHideWindow = "[Reserves] Hide list window"
Diag.E.LogReservesImportWindowMissing = "[Reserves] RMAImportWindow not found"
Diag.D.LogReservesFrameLoaded = "[Reserves] Frame loaded"
Diag.D.LogReservesBindButton = "[Reserves] Bind button=%s action=%s"
Diag.D.LogReservesItemInfoReceived = "[Reserves] Item info received itemId=%d"
Diag.D.LogReservesItemInfoPending = "[Reserves] Item info still pending itemId=%d"
Diag.D.LogReservesUILocalized = "[Reserves] UI localized %s"
Diag.D.LogReservesUIAlreadyLocalized = "[Reserves] UI already localized"
Diag.D.LogReservesPlayerFound = "[Reserves] Player found %s data=%s"
Diag.D.LogReservesPlayerNotFound = "[Reserves] Player not found %s"
Diag.D.LogReservesFetchAll = "[Reserves] Fetch all players=%d"
Diag.W.LogReservesImportFailedEmpty = "[Reserves] Import failed: empty or invalid data"
Diag.D.LogReservesParseStart = "[Reserves] Parse CSV start"
Diag.D.LogReservesParseComplete = "[Reserves] Parse CSV complete players=%d"
Diag.D.LogReservesImportRows = "[Reserves] Import rows valid=%d skipped=%d header=%s lines=%d"
Diag.D.LogReservesImportWrongModePlus = "[Reserves] Wrong CSV for Plus System; player=%s has multiple entries"
Diag.D.LogReservesEncodedImportStart = "[Reserves] Parsing encoded SoftRes payload"
Diag.D.LogReservesEncodedImportRows = "[Reserves] Encoded SoftRes import rows=%d players=%d source=%s"
Diag.W.LogReservesEncodedImportFailed = "[Reserves] Encoded SoftRes import failed: %s"
Diag.E.LogReservesOptionNotificationFailed = "[Reserves] Import mode committed, but OptionChanged failed: %s"
Diag.D.LogReservesAliasSet = "[Reserves] Alias set reserve=%s raid=%s"
Diag.D.LogReservesAliasCleared = "[Reserves] Alias cleared reserve=%s"
Diag.D.LogReservesQueryItemInfo = "[Reserves] Query item info itemId=%d"
Diag.D.LogReservesItemInfoReady = "[Reserves] Item info ready itemId=%d name=%s"
Diag.D.LogReservesItemInfoPendingQuery = "[Reserves] Item info pending itemId=%d"
Diag.D.LogReservesQueryMissingItems = "[Reserves] Query missing items"
Diag.D.LogReservesMissingItems = "[Reserves] Missing items requested=%d"
Diag.D.LogReservesFormatPlayers = "[Reserves] Format players itemId=%d"
Diag.D.LogReservesPlayersList = "[Reserves] Players itemId=%d list=%s"

-- Logger --
Diag.E.LogListUIError = "[ListUI:%s] %s"
Diag.D.LogListUIShow = "[ListUI] show %s -> %s"
Diag.D.LogListUIWidgets = "[ListUI:%s] widgets sf=%s sc=%s sfW=%.1f sfH=%.1f scW=%.1f scH=%.1f"
Diag.W.LogListUIMissingWidgets = "[ListUI:%s] Missing ScrollFrame widgets for %s"
Diag.D.LogListUIDeferLayout = "[ListUI:%s] defer (layout not ready): sfW=%.1f"
Diag.D.LogListUIFetch = "[ListUI:%s] fetch count=%d sfW=%.1f sfH=%.1f scW=%.1f scH=%.1f frameW=%.1f frameH=%.1f"
Diag.D.LogLoggerSelectInit = "[LoggerSelect] init ctx=%s ver=%d"
Diag.D.LogLoggerSelectToggle = "[LoggerSelect] toggle ctx=%s id=%s multi=%s action=%s count %d->%d ver=%d"
Diag.D.LogLoggerSelectAnchor = "[LoggerSelect] anchor ctx=%s from=%s to=%s ver=%d"
Diag.D.LogLoggerSelectRange = "[LoggerSelect] range ctx=%s id=%s add=%s action=%s count %d->%d ver=%d anchor=%s"
Diag.D.LogLoggerSelectClickRaid =
	"[LoggerSelect] click list=Raid id=%s ctrl=%d shift=%d action=%s selectedCount=%d focus=%s"
Diag.D.LogLoggerSelectClickBoss =
	"[LoggerSelect] click list=Boss id=%s ctrl=%d shift=%d action=%s selectedCount=%d focus=%s"
Diag.D.LogLoggerSelectClickBossAttendees =
	"[LoggerSelect] click list=BossAttendees id=%s ctrl=%d shift=%d action=%s selectedCount=%d focus=%s"
Diag.D.LogLoggerSelectClickRaidAttendees =
	"[LoggerSelect] click list=RaidAttendees id=%s ctrl=%d shift=%d action=%s selectedCount=%d focus=%s"
Diag.D.LogLoggerSelectClickLoot =
	"[LoggerSelect] click list=Loot id=%s ctrl=%d shift=%d action=%s selectedCount=%d focus=%s"
Diag.D.LogLoggerSelectClickContextMenu = "[LoggerSelect] click id=%s ctrl=0 action=CONTEXT_MENU(%s) selectedCount=%d"
Diag.D.LogLoggerSelectDeleteItems = "[LoggerSelect] delete items removed=%d"
Diag.W.ErrLoggerUpdateRosterNotInRaid = "[Logger] Cannot update roster: you are not in a raid."
Diag.W.ErrLoggerUpdateRosterNotCurrent = "[Logger] Cannot update roster: selected raid is not the current raid."
Diag.D.LogLoggerLootLogAttempt = "[Logger] loot entry attempt source=%s raidId=%s lootNid=%s "
	.. "looter=%s type=%s roll=%s lastBoss=%s"
Diag.E.LogLoggerNoRaidSession = "[Logger] loot entry FAILED no raid session raidId=%s lootNid=%s"
Diag.E.LogLoggerLootNidExpected =
	"[Logger] loot entry expected lootNid but got raw itemId raidId=%s value=%s link=%s matches=%d"
Diag.E.LogLoggerItemNotFound = "[Logger] loot entry FAILED item not found raidId=%d lootNid=%s lootCount=%d"
Diag.W.LogLoggerLooterEmpty = "[Logger] loot entry looter empty raidId=%d lootNid=%s link=%s"
Diag.W.LogLoggerRollTypeNil = "[Logger] loot entry rollType nil raidId=%d lootNid=%s looter=%s"
Diag.D.LogLoggerLootBefore = "[Logger] loot entry BEFORE raidId=%d lootNid=%s link=%s "
	.. "prevLooter=%s prevType=%s prevRoll=%s"
Diag.W.LogLoggerLootOverwrite = "[Logger] Loot overwrite raidId=%d lootNid=%s link=%s from=%s to=%s"
Diag.D.LogLoggerLootRecorded = "[Logger] Loot recorded source=%s raidId=%d lootNid=%s link=%s -> "
	.. "looter=%s type=%s roll=%s"
Diag.E.LogLoggerVerifyFailed = "[Logger] loot entry VERIFY FAILED raidId=%d lootNid=%s "
	.. "got(looter=%s type=%s roll=%s)"
Diag.D.LogLoggerVerified = "[Logger] loot entry verified raidId=%d lootNid=%s"
Diag.D.LogLoggerRecordedNoBossContext = "[Logger] Loot recorded without boss context raidId=%d lootNid=%s link=%s"
Diag.D.LogLoggerBossLootRemoved = "[Logger] Boss delete removed loot raidId=%d bossId=%d removed=%d"
Diag.W.LogLoggerSelectRaidPayloadInvalid = "[Logger] LoggerSelectRaid payload invalid raidId=%s reason=%s"

-- Raid synchronization --
Diag.D.LogRaidSyncTrace = "[RaidSync] event=%s %s"
Diag.D.LogRaidHistoryShareTrace = "[RaidHistory] event=%s %s"
