-- ----- RMA Lua Contract ----- --
-- deps: local addon = select(2, ...)
-- shared: direct addon namespace bindings
-- exports: publish module APIs on addon.*
-- events: none

local addon = select(2, ...)
local setmetatable = setmetatable
local tostring = tostring
local rawset = rawset

local L = addon.L
setmetatable(L, {
	__index = function(self, k)
		if k ~= nil then
			rawset(self, k, tostring(k))
		end
		return tostring(k)
	end,
})

-- ----- Internal state ----- --

-- ----- Private helpers ----- --

-- ----- Public methods ----- --

-- ==================== Callbacks ==================== --
L.StrCbErrUsage = "Usage: RMA:registerCallback(event, callbacks)"

-- ==================== General Buttons ==================== --
L.BtnConfigure = "Configure"
L.BtnDefaults = "Defaults"
L.BtnEdit = "Edit"
L.BtnOpen = "Open"
L.BtnAdd = "Add"
L.BtnRemove = "Remove"
L.BtnRemoveShort = "X"
L.BtnResetShort = "R"
L.BtnDelete = "Delete"
L.MsgAttendanceRemoved = "Raid Attendance: removed %d attendance record(s). Raid history was preserved."
L.MsgAttendanceRemoveFailed = "Raid Attendance: no attendance record was removed."
L.WarnRaidDatabaseAuthorityReleased = "Raid database authority passed to %s. This client now holds a read-only replica."
L.WarnRaidDatabaseAuthorityReceived =
	"Raid database authority received from %s. Recovery is in progress; raid history writes are temporarily paused."
L.WarnRaidReentryRecoverySuspended =
	"Raid database recovery was suspended (%s). Recording remains paused and no raid copy was overwritten."
L.PopupRaidReentryConfirm =
	"Resume the previous raid?\nZone: %s\nSize: %d\nDifficulty: %s"
L.BtnUpdate = "Update"
L.BtnStart = "Start"
L.BtnStop = "Stop"
L.BtnResume = "Resume"
L.BtnSave = "Save"
L.BtnCancel = "Cancel"
L.BtnClear = "Clear"
L.BtnCancelRemainingAwards = "Cancel Remaining Awards"
L.BtnClearAll = "Clear All"
L.BtnImport = "Import"
L.BtnRefresh = "Refresh"
L.BtnPreview = "Preview"
L.BtnLoggerPurgeHistory = "Purge"
L.BtnLoggerRebuildSources = "Rebuild"
L.BtnLoggerCleanUp = "Clean Up"
L.BtnLoggerScanHistory = "Scan"
L.BtnConfigPresetQuiet = "Quiet"
L.BtnConfigPresetStandard = "Standard"
L.BtnConfigPresetVerbose = "Verbose"
L.BtnGroupLoot = "Group Loot"
L.BtnKeepMasterLoot = "Keep Master Loot"
L.BtnAnnounce = "Announce"
L.BtnShare = "Share"
L.BtnAccept = "Accept"
L.BtnDecline = "Decline"
L.BtnLoggerSendRaid = "Send selected raid"

-- ==================== Item Quality ==================== --
L.StrLootQualityPoor = "Poor"
L.StrLootQualityUncommon = "Uncommon"
L.StrLootQualityRare = "Rare"
L.StrLootQualityEpic = "Epic"
L.StrLootQualityLegendary = "Legendary"

-- ==================== Minimap Button ==================== --
L.StrMinimapLClick = "|cffffd700Left-Click|r to access menu"
L.StrMinimapRClick = "|cffffd700Right-Click|r to access settings"
L.StrMinimapSClick = "|cffffd700Shift+Click|r to move"
L.StrMinimapAClick = "|cffffd700Alt+Click|r for free drag and drop"
L.StrLootMaster = "Loot Master"
L.StrQuickBar = "Show QuickBar"
L.BtnQuickBarML = "ML"
L.BtnQuickBarGL = "GL"
L.BtnQuickBarHIS = "HIS"
L.BtnQuickBarSR = "SR"
L.BtnQuickBarRW = "RW"
L.StrQuickBarHandleTooltip = "Drag to move the QuickBar"
L.StrQuickBarMasterLootTooltip = "Master Loot"
L.StrQuickBarGroupLootTooltip = "Group Loot"
L.StrQuickBarHistoryTooltip = "Loot History"
L.StrQuickBarSoftResTooltip = "SoftRes"
L.StrQuickBarRaidWarningTooltip = "Raid Warning"
L.PopupQuickBarMasterLoot = "Change the raid loot method to Master Loot?"
L.PopupQuickBarGroupLoot = "Change the raid loot method to Group Loot?"
L.StrLootReserve = "Loot Reserve"
L.StrLootHistory = "Loot History"
L.StrRaidAttendance = "Raid Attendance"
L.StrLootCounter = "Loot Counter"
L.StrLFMSpam = "LFM Spam"
L.StrClearIcons = "Clear Raid Icons"

-- ==================== Loot Master Frame ==================== --
L.BtnLootCounter = "Loot Counter"
L.BtnLootBans = "Loot Bans"
L.BtnLootCounterAnnounce = "Spam Counter"
L.BtnLootCounterResetAll = "Reset All"
L.TipLootCounterPlus = "Increment count"
L.TipLootCounterMinus = "Decrement count"
L.TipLootCounterReset = "Reset count to 0"
L.TipLootCounterAnnounce = "Announce MS/OS/FREE counts grouped by +N in raid chat."
L.TipLootCounterResetAll = "Reset all player counts to 0."
L.BtnInsertList = "Import SoftRes"
L.BtnOpenList = "Open SoftRes"
L.BtnSelectItem = "Select Item"
L.BtnRemoveItem = "Remove Item"
L.BtnSpamLoot = "Spam Loot"
L.BtnManual = "Manual"
L.BtnMS = "MS"
L.BtnOS = "OS"
L.BtnSR = "SR"
L.BtnFree = "Free"
L.StrTradeReason = "Reason"
L.BtnNeed = "NE"
L.BtnGreed = "GR"
L.BtnRoll = "Roll"
L.BtnCountdown = "Countdown"
L.BtnAward = "Award"
L.BtnReroll = "Reroll"
L.BtnHold = "Hold"
L.BtnBank = "Bank"
L.BtnDisenchant = "DE"
L.StrNoItemSelected = "No item selected"
L.StrRaidGridTitle = "Assign Loot"
L.StrRaidGridSelectorTitle = "Grid Selector"
L.StrRaidGridTargetTitle = "Select Target"
L.StrRaidGridDebugTitle = "Raid Grid Debug"
L.StrRaidGridEmpty = "No eligible players found."
L.StrLootBansTitle = "Loot Bans"
L.StrLootBansEmpty = "No raid players available."
L.StrLootBanTooltipTitle = "Loot Ban"
L.PopupLootBanApply = "Apply a Loot Ban to %s. Add an optional note:"
L.PopupLootBanUpdate = "Update the Loot Ban for %s:"
L.BtnApplyBan = "Apply Ban"
L.BtnUpdateBan = "Update Ban"
L.BtnRemoveBan = "Remove Ban"
L.StrMasterStatusIdle = "Select or drag an item to start."
L.StrMasterStatusReady = "Ready. Start a roll or use Hold, Bank, or DE."
L.StrMasterStatusRolling = "Rolls are open. Responses: %d."
L.StrMasterStatusRollingBypassed = "Rolls are open. Countdown bypassed. Responses: %d."
L.StrMasterStatusCountdown = "Countdown running. Awarding unlocks when the timer ends."
L.StrMasterStatusResolveTie = "Tie at the cutoff. Select winners manually before awarding."
L.StrMasterStatusSelectWinners = "Select %d winner(s) before awarding."
L.StrMasterStatusAwardTarget = "Ready to award: %s."
L.StrMasterStatusAwardSelection = "Ready to award %d winner(s)."
L.StrMasterStatusTrade = "Trade in progress with %s."
L.StrMasterStatusInventory = "Inventory item mode. Select winners and use Trade."
L.StrMasterStatusInventoryTarget = "Ready to trade: %s."
L.StrMasterStatusInventorySelection = "Ready to trade %d winner(s)."
L.StrMasterStatusMultiAward = "Multi-award %d/%d: %s."
L.StrMasterStatusPickWinner = "Pick a winner before continuing."
L.StrMasterStatusSuggestion = "Ready. Suggestion: %s."
L.StrMasterStatusReadyWithSummary = "Ready. %s."
L.StrMasterStatusRollingWithSummary = "Rolls are open. %s. Responses: %d."
L.StrMasterSessionWinnerSummary = "Winner: %s"
L.StrMasterSessionTieSummary = "Tie: %s"
L.StrRollSrSummaryPresentMissing = "SR %d present / %d missing"
L.StrRollSrSummaryPresent = "SR %d present"
L.StrRollSrSummaryNoPresent = "No present SR"
L.StrRollSrSummaryFallback = "Free roll fallback"
L.StrRollLootCopies = "Copies: %d"
L.StrAutoLootSuggestionSkipLogger = "skip logger"
L.TipMasterConfig = "Open RMA settings and UI options."
L.TipMasterSelectItem = "Pick the next item from the loot window."
L.TipMasterRemoveItem = "Remove the current inventory item and return to loot-window selection."
L.TipMasterSpamLoot = "Announce the current loot list to the raid."
L.TipMasterPickWinner = "Pick a winner before continuing."
L.TipMasterReadyCheck = "Send a ready-check style reminder before trading inventory loot."
L.TipMasterRollMode = "Start a %s roll for the current item."
L.TipMasterRollModeMultiple = "Start a %s roll for the current item and resolve %d winner(s) at the cutoff."
L.TipMasterSRUnavailable = "This item has no SoftRes entries yet. Import or open the reserve list first."
L.TipMasterCountdown = "Left-click starts or stops the countdown. Right-click closes rolls immediately."
L.TipMasterCountdownInactive = "Start a roll first, then use the countdown to close intake."
L.TipMasterAward = "Award the current item to %s."
L.TipMasterAwardMultiple = "Award the current item to %d selected winner(s)."
L.TipMasterTrade = "Trade the current inventory item to %s."
L.TipMasterTradeMultiple = "Trade the current inventory item across %d selected winner(s)."
L.TipMasterReroll = "Start a tiebreak reroll for the players tied at the cutoff."
L.TipMasterHold = "Assign the current item to %s for later distribution."
L.TipMasterHoldUnset = "Assign the current item to the configured holder."
L.TipMasterBank = "Assign the current item to %s for bank storage."
L.TipMasterBankUnset = "Assign the current item to the configured banker."
L.TipMasterDisenchant = "Assign the current item to %s for disenchanting."
L.TipMasterDisenchantUnset = "Assign the current item to the configured disenchanter."
L.TipMasterReserveImport = "Open the SoftRes import window."
L.TipMasterReserveList = "Open the SoftRes list for the current raid."
L.TipMasterRollSelf = "Submit your own roll to the active session."
L.TipMasterClear = "Clear recorded rolls for the current item."
L.TipMasterCancelRemainingAwards = "Cancel future awards. The current item transfer, if already started, may still finish."
L.TipMasterLootCounter = "Open the loot counter widget."
L.TipRaidGridClickAward = "Click to assign loot."
L.TipRaidGridClickTarget = "Click to select this target."
L.TipRaidGridClickDebug = "Debug preview only."
L.PopupRaidGridConfirm = "Give %s to %s?"
L.StrLootReservedBy = "Reserved by"
L.StrCounter = "Count"
L.StrInfo = "Info"
L.StrTrashMobName = "Trash Mob"
L.StrRoll = "Roll"
L.StrRolls = "Rolls"
L.StrRollLow = "Low"
L.StrRollHigh = "High"
L.StrRollDuplicateTag = "DUP"
L.StrRollRerollOnlyTag = "REROLL"
L.ChatSpamLoot = "The boss dropped:"
L.ChatSpamLootFrom = "%s dropped:"
L.ChatSpamLootReservedHeader = "Item reserved:"
L.ChatSpamLootReservedLine = "%d. %s by %s"
L.StrLootCounterAnnounceHeader = "MS Counter:"
L.StrLootCounterAnnounceNone = "MS Counter: no MS awards yet."
L.StrLootCounterAnnounceHeaderOs = "OS Counter:"
L.StrLootCounterAnnounceNoneOs = "OS Counter: no OS awards yet."
L.StrLootCounterAnnounceHeaderFree = "FREE Counter:"
L.StrLootCounterAnnounceNoneFree = "FREE Counter: no FREE awards yet."
L.StrConfirmLootCounterResetAll = "Are you sure you want to reset all loot counts?"
L.ChatReadyCheck = "Ready Check before rolling items!"
L.WarnReadyCheckNotAllowed = "Ready Check requires party lead or raid assist/lead."
L.WarnLootCounterBroadcastNotAllowed = "Counter announce requires raid lead or assist."
L.WarnRaidWarningFallback = "No Raid Warning permission: announcing to RAID chat."
L.ChatRollMS = "Roll for MS on: %s"
L.ChatRollMSMultipleHigh = "Roll High for MS on: %s x%d"
L.ChatRollMSMultipleLow = "Roll Low for MS on: %s x%d"
L.ChatRollOS = "Roll for OS on: %s"
L.ChatRollOSMultipleHigh = "Roll High for OS on: %s x%d"
L.ChatRollOSMultipleLow = "Roll Low for OS on: %s x%d"
L.ChatRollSR = "Roll %s for SR on: %s"
L.ChatRollSRMultipleHigh = "Roll High %s for SR on: %s x%d"
L.ChatRollSRMultipleLow = "Roll Low %s for SR on: %s x%d"
L.ChatRollFree = "Free roll on: %s"
L.ChatRollFreeMultipleHigh = "Free roll High on: %s x%d"
L.ChatRollFreeMultipleLow = "Free roll Low on: %s x%d"
L.ChatCountdownTic = "Rolling ends in %d sec"
L.ChatCountdownEnd = "Rolling ends now!"
L.ChatCountdownBlock = "Rolls are ignored after countdown!"
L.ChatAward = "Congrats! %s won %s"
L.ChatAwardMutiple = "Congrats! %s have won %s"
L.ChatTrade = "Congrats {triangle} %s ! Please trade {star} %s"
L.ChatTradeMutiple = "Winners are: %s, Please trade {star} %s"
L.ChatHold = "%s is holding %s for later roll"
L.ChatBank = "%s is holding %s for the bank"
L.ChatDisenchant = "%s will be disenchanted by %s"
L.ChatNoneRolledHold = "No one rolled on %s, %s is holding it"
L.ChatNoneRolledBank = "No one rolled on %s, %s holds it for bank"
L.ChatNoneRolledDisenchant = "No one rolled on %s, %s will disenchant it"
L.ChatOnlyRollOnce = "Roll: you have used all allowed rolls for this item."
L.ChatRollNotInRaid = "Roll ignored: you are not in raid."
L.ChatRollExcluded = "Roll ignored: you are excluded from this item."
L.ChatRollInactive = "Roll ignored: no active roll session."
L.ChatRollTieOnly = "Roll ignored: only tied players may reroll this item."
L.ChatTieReroll = "Tie reroll for %s on: %s"
L.WhisperHoldTrade = "RMA > Please trade me to hold %s"
L.WhisperBankTrade = "RMA > Please trade me to hold %s (reserved)"
L.WhisperDisenchantTrade = "RMA > Please trade me to disenchant %s"
L.WhisperHoldAssign = "RMA > You received an item to hold: %s (for later)"
L.WhisperBankAssign = "RMA > You received a reserved item: %s (reserved)"
L.WhisperDisenchantAssign = "RMA > You received an item to disenchant: %s"
L.ErrScreenReminder = "Please take a screenshot before trading, you never know!"
L.ErrItemStack = "You have a stack of %s, you may want to split it first"
L.ErrCannotFindItem = "Cannot find item: %s"
L.ErrCannotFindPlayer = "Cannot find player: %s"
L.WarnMLNoPermission = "Cannot award: you do not have Loot Master access."
L.WarnMLOnlyMode = "Action blocked: Loot Master access is required."
L.WarnInventoryTradeNoPermission = "Action blocked: raid leadership or Loot Master access is required."
L.WarnMLNoCandidatesAvailable = "Cannot award: no Master Loot candidates available."
L.WarnMLWinnerNoCandidate = "Cannot award: %s is not a valid Master Loot candidate."
L.WarnMLAwardConfirmationUncertain =
	"Award confirmation is uncertain for %s to %s (%s). The pending award will be retried on confirmation."
L.WarnMLAwardConfirmationUnresolved =
	"Award confirmation could not be resolved for %s to %s. Future multi-award entries were stopped."
L.WarnMLMultiAwardTimerScheduleFailed = "Multi-award stopped because its timer could not be scheduled."
L.WarnMLLootAttributionFailed = "Loot attribution could not be finalized safely (%s). Review loot history."
L.ErrMLLootSlotChanged = "Cannot award: the selected loot slot changed before the client assignment."
L.ErrMLAwardConfirmationScheduleFailed = "Cannot award: the confirmation timer could not be scheduled."
L.ErrMLGiveMasterLootFailed = "Cannot award: the client rejected the Master Loot assignment."
L.ErrMLWinnerNameUnresolved = "Cannot award: winner name is empty or unresolved."
L.ErrMLWinnerNotInRaid = "Cannot award: %s is not in raid."
L.ErrMLWinnerExcluded = "Cannot award: %s is manually excluded from this roll."
L.ErrMLWinnerIneligible = "Cannot award: %s is not eligible for this roll."
L.ErrMLWinnerPassed = "Cannot award: %s has passed on this item."
L.ErrMLWinnerCancelled = "Cannot award: %s withdrew their response for this item."
L.ErrMLWinnerTimedOut = "Cannot award: %s timed out for this item."
L.ErrMLWinnerNoRoll = "Cannot award: %s has no active roll response."
L.ErrMLWinnerTieUnresolved = "Cannot award: tie at the winner cutoff. Select winners manually."
L.ErrMLWinnerLootBanned = "Cannot award: %s has an active Loot Ban."
L.ErrMLWinnerLootBannedWithNote = "Cannot award: %s has an active Loot Ban. Reason: %s"
L.ErrLootBanNoteTooLong = "Loot Ban notes cannot exceed 240 characters."
L.ErrLootBanNoteAscii = "Loot Ban notes must use ASCII characters only."
L.ErrMLInventorySoulbound = "Only non-soulbound or tradeable items can be added: %s"
L.ErrMLInventoryItemMissing = "Cannot find the item in your bags: %s"
L.WarnTradeManualReasonMissing = "Manual trade slot %s was not auto-logged because no reason was selected."
L.WarnTradeTransferUnverified = "Trade transfer for %s to %s could not be verified from inventory; no award was recorded."
L.ErrNoWinnerSelected = "No winner selected. Use Roll or Select Winner first."
L.StrRollTieTag = "TIE"
L.StrRollPassTag = "PASS"
L.StrRollCancelledTag = "CXL"
L.StrRollTimedOutTag = "OOT"
L.StrRollOutTag = "OUT"
L.StrRollBlockedTag = "BLK"
L.StrRollLootBanTag = "BAN"

-- ==================== Configuration Frame ==================== --
L.StrConfigPanelTitle = "RMA"
L.StrConfigPanelMasterLoot = "Master Loot"
L.StrConfigPanelQuickBar = "QuickBar"
L.StrConfigPanelRaidWarning = "Raid Warning"
L.StrConfigPanelHelp = "Help"
L.StrConfigRootOverviewTitle = "Raid Management Addon"
L.StrConfigRootOverviewBody =
	"RMA is a raid-leader toolkit for Wrath raids. Use the subpanels on the left to configure each workflow."
L.StrConfigRootWhatTitle = "What it does"
L.StrConfigRootWhatBody =
	"Manages master-loot rolls, loot history, raid-warning messages, LFM spam, SoftRes hints, and loot counters."
L.StrConfigRootHowTitle = "How it works"
L.StrConfigRootHowBody =
	"RMA stores raid data locally, updates it from raid events and chat, and can sync current raid history with other RMA users."
L.StrConfigRootWhyTitle = "Why use it"
L.StrConfigRootWhyBody =
	"It keeps repeated raid tasks consistent, auditable, and faster without replacing Blizzard loot rules or assigning loot automatically."
L.StrConfigQuickBarOrientation = "Orientation"
L.StrConfigQuickBarOrientationDesc = "Choose a horizontal or vertical QuickBar layout."
L.StrConfigQuickBarHorizontal = "Horizontal"
L.StrConfigQuickBarVertical = "Vertical"
L.StrConfigQuickBarShowML = "Show ML"
L.StrConfigQuickBarShowGL = "Show GL"
L.StrConfigQuickBarShowSR = "Show SR"
L.StrConfigQuickBarShowHIS = "Show HIS"
L.StrConfigQuickBarShowRW = "Show RW"
L.StrConfigQuickBarShowMLDesc = "Show the Master Loot button."
L.StrConfigQuickBarShowGLDesc = "Show the Group Loot button."
L.StrConfigQuickBarShowSRDesc = "Show the SoftRes button."
L.StrConfigQuickBarShowHISDesc = "Show the Loot History button."
L.StrConfigQuickBarShowRWDesc = "Show the Raid Warning button."
L.StrConfigSortAscending = "Sort rolls ascending"
L.StrConfigUseRaidWarning = "Use raid warnings"
L.StrConfigAnnounceOnWin = "Announce loot items winners"
L.StrConfigAnnounceOnHold = "Announce items held for later roll"
L.StrConfigAnnounceOnBank = "Announce reserved items (bank)"
L.StrConfigAnnounceOnDisenchant = "Announce items to be disenchanted"
L.StrConfigLootWhisper = "Send whispers to loot holder, banker and disenchanter."
L.StrConfigSoftResWhisperReplies = "Reply to SoftRes whispers"
L.StrConfigCountdownRollsBlock = "Ignore all rolls done after countdown"
L.StrConfigScreenReminder = "ScreenShot reminder before trading an item"
L.StrConfigIgnoreStacks = "Allow trading a stack of an item"
L.StrConfigShowTooltips = "Show items tooltips"
L.StrConfigShowLootCounterDuringMSRoll = "Show loot counter during MS roll"
L.StrConfigMinimapButton = "Show minimap button"
L.StrConfigAutoMasterLootOnBossTarget = "Auto Master Loot on boss target"
L.StrConfigAutoMasterLootNoticeSeconds = "Auto Master Loot message seconds"
L.StrConfigAskGroupLootAfterBossLoot = "Ask to restore Group Loot after boss loot"
L.StrConfigAutoSpamLootOnLootOpened = "Spam loot when loot opens"
L.StrConfigAutoSpamSoftResOnLootOpened = "Spam SoftRes for opened loot"
L.StrConfigCountdownDuration = "Countdown Duration"
L.StrConfigCountdownSimpleRaidMsg = "Simple raid messages for countdown"
L.StrConfigSortAscendingDesc = "Shows lower roll values first in roll lists."
L.StrConfigUseRaidWarningDesc = "Uses Raid Warning for countdown and loot messages when available."
L.StrConfigAnnounceOnWinDesc = "Announces the player who wins a rolled item."
L.StrConfigAnnounceOnHoldDesc = "Announces items kept for a later roll."
L.StrConfigAnnounceOnBankDesc = "Announces items reserved for the bank."
L.StrConfigAnnounceOnDisenchantDesc = "Announces items assigned for disenchanting."
L.StrConfigLootWhisperDesc = "Sends whispers to the loot holder, banker, and disenchanter."
L.StrConfigSoftResWhisperRepliesDesc = "Replies to SoftRes whisper checks when allowed."
L.StrConfigCountdownRollsBlockDesc = "Excludes rolls sent after the countdown ends."
L.StrConfigScreenReminderDesc = "Shows a screenshot reminder before item trade."
L.StrConfigIgnoreStacksDesc = "Allows trading an item stack when the loot is stacked."
L.StrConfigShowTooltipsDesc = "Shows RMA item details in item tooltips."
L.StrConfigShowLootCounterDuringMSRollDesc = "Displays the loot counter while an MS roll is active."
L.StrConfigMinimapButtonDesc = "Shows or hides the RMA minimap launcher."
L.StrConfigAutoMasterLootOnBossTargetDesc =
	"When you are raid leader, switches to Master Loot after targeting a recognized raid boss."
L.StrConfigAutoMasterLootNoticeSecondsDesc =
	"Controls how long the short Auto Master Loot screen message stays visible."
L.StrConfigAskGroupLootAfterBossLootDesc =
	"After boss loot is cleared in Master Loot, asks before switching the raid back to Group Loot."
L.StrConfigAutoSpamLootOnLootOpenedDesc = "When you are Master Looter, announces opened loot automatically."
L.StrConfigAutoSpamSoftResOnLootOpenedDesc =
	"Adds SoftRes player lines only for opened items with current-raid reserves."
L.StrConfigCountdownDurationDesc = "Controls how many seconds a roll countdown lasts."
L.StrConfigCountdownSimpleRaidMsgDesc = "Uses shorter Raid Warning countdown messages."
L.StrConfigMasterLootPresetsTitle = "Recommended Presets"
L.StrConfigMasterLootPresetDefaultsTitle = "Defaults"
L.StrConfigMasterLootPresetDefaultsDesc = "Restore the baseline RMA Master Loot configuration."
L.StrConfigMasterLootPresetQuietTitle = "Quiet"
L.StrConfigMasterLootPresetQuietDesc = "Keeps essential announcements with fewer raid-warning messages."
L.StrConfigMasterLootPresetStandardTitle = "Standard"
L.StrConfigMasterLootPresetStandardDesc = "Balanced raid warnings for regular raid leading."
L.StrConfigMasterLootPresetVerboseTitle = "Verbose"
L.StrConfigMasterLootPresetVerboseDesc = "Enables detailed countdown and loot announcement output."
L.StrConfigMasterLootAnnouncementPreviewTitle = "Announcement Preview"
L.StrConfigMasterLootPreviewSimple = "simple raid-warning text"
L.StrConfigMasterLootPreviewDetailed = "detailed raid-warning text"
L.StrConfigMasterLootPreviewWin = "Winner announce channel: %s"
L.StrConfigMasterLootPreviewHold = "Hold announce: %s"
L.StrConfigMasterLootPreviewBank = "Bank announce: %s"
L.StrConfigMasterLootPreviewDisenchant = "Disenchant announce: %s"
L.StrConfigMasterLootPreviewCountdown = "Countdown: %s sec, %s"
L.StrConfigHelpMasterLootTitle = "Master Loot"
L.StrConfigHelpMasterLootBody = "/rma ml: open Master Loot.\n"
	.. "/rma counter: open Loot Counter.\n"
	.. "/rma config: open the configuration popup.\n"
	.. "/rma config reset: restore default options."
L.StrConfigHelpLootHistoryTitle = "Loot History"
L.StrConfigHelpLootHistoryBody = "/rma logger [share]: open Loot History or offer a completed raid.\n"
	.. "/rma attendance: open Raid Attendance."
L.StrConfigHelpLFMSpamTitle = "LFM Spam"
L.StrConfigHelpLFMSpamBody = "/rma lfm, /rma pug, /rma group, /rma grouper:\n"
	.. "show LFM Spam commands.\n"
	.. "/rma lfm start: start LFM spam.\n"
	.. "/rma lfm stop: stop LFM spam.\n"
	.. "/rma ach [link]: print achievement ID."
L.StrConfigHelpRaidWarningTitle = "Raid Warning"
L.StrConfigHelpRaidWarningBody = "/rma rw, /rma warn, /rma warning, /rma warnings:\n"
	.. "show Raid Warning commands.\n"
	.. "/rma rw [ID]: announce warning by ID."
L.StrConfigHelpCommandPermissionsTitle = "Command Permissions"
L.StrConfigHelpCommandPermissionsBody = "Master Looter: item actions, loot assignment, trade reminders.\n"
	.. "Raid leader or assistant: Raid Warning, grouped Loot Counter, LFM group spam.\n"
	.. "Local only: Help, config, bug, version, preview, and history scan."
L.StrConfigHelpDiagnosticsTitle = "Diagnostics"
L.StrConfigHelpDiagnosticsBody = "/rma bug: print a local support summary.\n"
L.StrConfigHelpCommandsTitle = "Command reference"
L.StrConfigHelpDebugCommandsTitle = "Debug commands"
L.StrConfigHelpCommandsBody = "/rma help [topic]: show command help in chat.\n\n"
	.. "/rma config [reset]; /rma ml; /rma counter; /rma logger [share]; /rma attendance; /rma warnings; /rma lfm [start|stop]; /rma reserves [import].\n\n"
	.. "/rma reserves check; /rma reserves alias <softres-name> <raid-name>; /rma reserves unalias <softres-name>; /rma reserves aliases; /rma reserves sync; /rma reserves meta; /rma reserves clearcache.\n\n"
	.. "/rma ach <achievement-id>; /rma specinspect [force]; /rma validate raids [verbose]; /rma minimap [show|hide|pos <0-360>]; /rma perf [on|off|threshold <ms>|report|audit|items|reset]; /rma version [local]; /rma bug.\n\n"
	.. "Aliases: config/conf/options/opt; lfm/pug/group/grouper; warnings/warning/warn/rw; reserves/res/reserve/sr/softres; debug/dbg/debugger; minimap/mm; version/ver/about; bug/report.\n"
	.. "/rma version: print addon details and request group versions.\n"
	.. "/rma perf on|off: toggle slow-block diagnostics."
L.MsgAutoMasterLootSet = "RMA: Loot method set to Master Loot for %s."
L.MsgAutoMasterLootScreen = "Boss targeted, auto switch to Master Loot."
L.MsgGroupLootRestored = "RMA: Loot method set to Group Loot."
L.MsgQuickBarLootMethodUnsupported = "RMA: Unsupported loot method."
L.MsgQuickBarRaidRequired = "RMA: You must be in a raid to change the loot method."
L.MsgQuickBarLeaderRequired = "RMA: Only the raid leader can change the loot method."
L.MsgQuickBarPlayerNameUnavailable = "RMA: Your player name is unavailable."
L.MsgQuickBarMasterLootSet = "RMA: Loot method set to Master Loot."
L.MsgQuickBarGroupLootSet = "RMA: Loot method set to Group Loot."
L.PopupGroupLootRestoreText = "Boss loot appears to be complete. Switch back to Group Loot?"
L.StrConfigLootHistoryReportTitle = "Loot History Report"
L.StrConfigLootHistoryReportSummary = "Raids: %d\n"
	.. "Empty raids: %d\n"
	.. "No boss encounter: %d\n"
	.. "Non epic loot: %d\n"
	.. "Missing sources: %d\n"
	.. "Invalid sources: %d\n"
	.. "Orphan loot: %d\n"
	.. "Duplicate candidates: %d"
L.StrConfigLootHistoryIgnoreGroupLoot = "Ignore GroupLoot"
L.StrConfigLootHistoryIgnoreGroupLootDesc = "Stops passive Group Loot messages from being recorded in Loot History."
L.StrConfigLootHistoryIgnoreSelectionThreshold = "Override raid loot threshold"
L.StrConfigLootHistoryIgnoreSelectionThresholdDesc =
	"Uses the Logger loot quality dropdown instead of the current raid loot threshold."
L.StrConfigLootHistoryLoggerLootQuality = "Logger loot quality"
L.StrConfigLootHistoryLoggerLootQualityDesc = "Records loot at or above this item quality when the override is enabled."
L.StrConfigLootHistoryDataHealthTitle = "Data Health"
L.StrConfigLootHistoryScanHistoryTitle = "Scan history"
L.StrConfigLootHistoryScanHistoryDesc =
	"Refreshes the report above and checks stored raid logs for empty raids, missing sources, invalid sources, orphan data, duplicate candidates, and player-name conflicts."
L.StrConfigLootHistoryMaintenanceTitle = "Maintenance"
L.StrConfigLootHistoryPurgeHistoryTitle = "Purge loot history"
L.StrConfigLootHistoryPurgeHistoryDesc = "Deletes every stored raid log and clears the current loot-history selection."
L.StrConfigLootHistoryRebuildSourcesTitle = "Rebuild loot sources"
L.StrConfigLootHistoryRebuildSourcesDesc =
	"Uses the static item source database to fill missing Source values on logged loot."
L.StrConfigLootHistoryCleanUpTitle = "Clean Up"
L.StrConfigLootHistoryCleanUpDesc =
	"Opens a selectable cleanup popup for empty raid logs, non-epic loot, and non-empty raids without boss encounters."
L.StrConfigLootHistoryCleanupPopupTitle = "Clean Up Loot History"
L.StrConfigLootHistoryCleanupPopupBody = "Select the raid-history data to delete."
L.StrConfigLootHistoryCleanupEmptyRaids = "Empty Raid"
L.StrConfigLootHistoryCleanupEmptyRaidsDesc = "Deletes raid logs with no players, bosses, loot, attendance, or changes."
L.StrConfigLootHistoryCleanupNonEpicLoot = "Non Epic Loot"
L.StrConfigLootHistoryCleanupNonEpicLootDesc = "Deletes logged loot below epic quality. Unknown-quality loot is kept."
L.StrConfigLootHistoryCleanupNoBossEncounter = "No Boss Encounter"
L.StrConfigLootHistoryCleanupNoBossEncounterDesc = "Deletes non-empty raid logs with no boss kills recorded."
L.StrConfigLFMSpamPreviewTitle = "Message Preview"
L.StrConfigLFMSpamPreviewPending = "Open LFM Spam or click Refresh to build a preview from the saved draft."
L.StrConfigLFMSpamPreviewLength = "Length: %d/255"
L.StrConfigLFMSpamSafetyTitle = "Safety"
L.StrConfigLFMSpamSafetyBody = "The spam service keeps the existing duration and message-count caps. Use Start and Stop here only "
	.. "after checking the preview and selected channels in the LFM Spam frame."
L.StrConfigRaidWarningTemplatesTitle = "Warning Templates"
L.StrConfigRaidWarningTemplatesBody = "Fresh installs include six stock warning templates. Use Preview to inspect "
	.. "saved warnings or Open to edit them."
L.StrConfigRaidWarningPreviewTitle = "Template Preview"
L.StrConfigRaidWarningPreviewPending = "Click Preview to list configured warnings."
L.StrConfigRaidWarningPreviewEmpty = "No raid warnings configured."
L.StrConfigRaidWarningPermissionTitle = "Permissions"
L.StrConfigRaidWarningPermissionBody = "Raid Warning announcements require raid leader or assistant permission. RMA falls back through "
	.. "the existing chat service when Raid Warning is unavailable."
L.StrConfigRaidWarningMaintenanceTitle = "Maintenance"
L.StrConfigRaidWarningClearSavedTitle = "Clear saved warnings"
L.StrConfigRaidWarningClearSavedDesc = "Deletes saved Raid Warning messages. The confirmation can keep or delete "
	.. "stock templates."
L.StrConfirmPurgeLootHistory = "Are you sure you want to purge all loot history? This cannot be undone."
L.StrConfirmClearRaidWarnings = "Do you want to delete stock warnings too?"

-- ==================== Raid Helper Reserves ==================== --
L.BtnClearReserve = "Clear Reserve"
L.BtnQueryItem = "Query Item"
L.StrRaidReserves = "Loot Reserve"
L.StrImportReservesTitle = "Import Loot Reserve"
L.StrImportReservesHint = "Choose import options, then paste your SoftRes data below:"
L.StrImportModeLabel = ""
L.StrImportModeMulti = "Multi-reserve"
L.StrImportModePlus = "Plus System"
L.StrImportReserveSystemLabel = "Reserve System"
L.StrImportFormatLabel = "Import Format"
L.StrImportFormatJson = "JSON"
L.StrImportFormatCsv = "CSV"
L.ErrCSVWrongForPlusShort = "Wrong CSV format for Plus System."
L.ErrCSVWrongForPlusWithPlayer =
	"Wrong CSV format for Plus System.\nPlayer '%s' has multiple reserve entries.\nSwitch to Multi-reserve or check your SoftRes settings."
L.ErrCSVWrongForPlus =
	"Wrong CSV format for Plus System.\nThis CSV contains players with multiple reserve entries.\nSwitch to Multi-reserve or check your SoftRes settings."
L.BtnSwitchToMulti = "Switch to Multi-reserve"
L.ErrImportReservesEmpty = "Import failed: empty or invalid reserve data."
L.WarnNoValidRows = "No valid rows found in CSV (check header)."
L.WarnReservesHeaderHint = "CSV header not detected. Expected columns include itemId and name."
L.WarnReservesEncodedImportCompressed = "Encoded SoftRes data appears compressed, but LibDeflate is not available."
L.WarnReservesEncodedImportInvalid = "Encoded SoftRes data could not be decoded."
L.SuccessReservesParsed = "Reserves parsed: %s"
L.MsgReservesAliasSet = "SoftRes alias set: %s -> %s."
L.MsgReservesAliasCleared = "SoftRes alias cleared: %s."
L.MsgReservesAliasInvalid = "SoftRes alias requires a reserve name and a raid name."
L.MsgReservesAliasesTitle = "SoftRes aliases:"
L.MsgReservesAliasesEmpty = "No SoftRes aliases configured."
L.BtnClose = "Close"
L.BtnSpamSoftResWhisper = "Spam msg"
L.StrReserveListAcceptSR = "Accept SR"
L.StrReserveListResponseWisp = "Response Wisp"
L.StrReserveListWhisperHelp = "Whisper ML +sr to see reserves.\n" .. "Whisper ML +sr [itemLink] to add one."
L.StrReserveListAcceptSRTooltipTitle = "Accept SR"
L.StrReserveListAcceptSRTooltipText = "Allows players to whisper +sr [itemLink] "
	.. "to add a reserve and receive a confirmation. This changes local reserve data."
L.StrReserveListResponseWispTooltipTitle = "Response Wisp"
L.StrReserveListResponseWispTooltipText = "Allows players to whisper +sr without an item link "
	.. "to receive their current reserves. This does not change reserve data."
L.StrReserveListStatus = "Players: %d - Reserved Players: %d"
L.BtnClearReserves = "Clear Loot Reserve"
L.StrConfirmClearReserves = "Clear all saved loot reserve data?"
L.StrConfirmApplyReserveEdits = "Apply %d reserve edit change(s)?"
L.ErrReserveEditRow = "Reserve edit row %d failed: %s"
L.ErrReserveEditInvalidPlayer = "player is no longer available"
L.ErrReserveEditMissingItem = "item is no longer reserved"
L.ErrReserveEditNoChange = "value is unchanged"
L.ErrReserveEditInvalidValue = "enter a valid value"
L.ErrReserveEditStale = "the row changed while confirmation was open; review the edits and try again"
L.ErrReserveEditFailed = "the changes could not be applied"
L.StrConfirmRemoveReserveRow = "Remove reserve for %s on item %s?"
L.StrReserveCountSuffix = " (x%d)"
L.StrReservesTooltipTitle = "Reserves"
L.StrReservesTooltipTotal = "Total: %d"
L.StrReservesTooltipShownHidden = "Shown: %d | Hidden: +%d"
L.StrReservesTooltipPlus = "P+%d: %s"
L.StrReservesTooltipQuantity = "x%d: %s"
L.StrReservesPlayersHiddenSuffix = " ... +%d"
L.StrReservesItemIdLabel = "Item ID: %s"
L.StrReservesTooltipDroppedBy = "Dropped by: %s"
L.StrReservesItemFallback = "[Item %s]"

-- ==================== Raid Warnings Frame ==================== --
L.StrMessage = "Message"
L.StrWarningsHelpTitle = "Tips:"
L.StrWarningsHelpBody =
	"- |cffffd700Left-Click|r to select a warning, click again to cancel selection.\n- |cffffd700Ctrl-Click|r for a quick raid warning.\n- When you select a warning, you can either |cffffd700Edit|r it, |cffffd700Delete|r it or |cffffd700Announce|r it using the provided buttons."
L.StrWarningsError =
	"Only the body of a message is required! Though, we recommend naming your warnings so you never get lost."
L.MsgWarningAnnounced = "Warning sent to %s."
L.MsgWarningLocalFallback = "You are not in a group. The warning was printed locally and was not sent."
L.ErrWarningAnnouncement = "Warning was not sent (%s)."
L.ErrWarningSave = "Warning was not saved (%s)."
L.ErrWarningNotification = "Warning data was saved, but its refresh notification failed (%s)."
L.ErrWarningClear = "Saved warnings were not cleared (%s)."
L.StrCmdWarningAnnounce = "announce the specified raid warning"
L.StrRaidWarningTemplatePullName = "Pull"
L.StrRaidWarningTemplatePullContent = "Pull in 10 seconds."
L.StrRaidWarningTemplateSpreadName = "Spread"
L.StrRaidWarningTemplateSpreadContent = "Spread out."
L.StrRaidWarningTemplateStackName = "Stack"
L.StrRaidWarningTemplateStackContent = "Stack on marker."
L.StrRaidWarningTemplateStopDpsName = "Stop DPS"
L.StrRaidWarningTemplateStopDpsContent = "Stop DPS now."
L.StrRaidWarningTemplateBloodlustName = "Bloodlust"
L.StrRaidWarningTemplateBloodlustContent = "Use Bloodlust/Heroism now."
L.StrRaidWarningTemplateBreakName = "Break"
L.StrRaidWarningTemplateBreakContent = "Break time. Be back soon."

-- ==================== LFM Spam Frame ==================== --
L.StrSpammer = "LFM Spam"
L.StrSpammerCompStr = "Raid Composition"
L.StrSpammerNeedStr = "Need"
L.StrSpammerMessageStr = "Message"
L.StrSpammerPreviewStr = "Preview"
L.StrSpammerErrLength = "Your LFM message is too long."
L.StrSpammerDurationHelp = "It is recommended to use at least 60 seconds to avoid server mute."
L.StrSpammerMessageHelp1 = "This will be added to the end of the generated message."
L.StrSpammerMessageHelp2 = "You can use |cffffd700{ID}|r to include achievements links."
L.StrSpammerMessageHelp3 =
	"You can find the achievement |cffffd700ID|r using the command: \n|cffffd700/rma ach [link]|r."

L.StrRaid = "Raid"
L.StrDuration = "Duration"
L.StrTank = "Tank"
L.StrHealer = "Healer"
L.StrMelee = "Melee"
L.StrRanged = "Ranged"
L.StrChannels = "Channels"
L.StrSpammerChannelUnavailable = "%s (unavailable)"
L.StrGuild = "Guild"
L.StrYell = "Yell"

-- ==================== Logger Frame ==================== --
L.StrNumber = "#"
L.StrDate = "Date"
L.StrZone = "Zone"
L.StrSize = "Size"
L.StrName = "Name"
L.StrCount = "Count"
L.StrPlayer = "Player"
L.StrMS = "MS"
L.StrOS = "OS"
L.StrFREE = "FREE"
L.StrClass = "Class"
L.StrDifficulty = "Difficulty"
L.StrTime = "Time"
L.StrMode = "Mode"
L.StrItem = "Item"
L.StrSource = "Source"
L.StrWinner = "Winner"
L.StrType = "Type"
L.BtnExport = "Export"
L.StrLootTab = "Loot"
L.StrAttendanceTab = "Attendance"
L.StrHistoryTab = "Loot"
L.StrLoggerLabelPlayer = "Player: %s"
L.StrLoggerEmptyRaids = "No raid logs yet. Enter a raid and log a boss or loot event to start history."
L.StrLoggerEmptyBossesSelectRaid = "Select a raid to inspect boss kills and trash entries."
L.StrLoggerEmptyBosses = "No bosses or trash entries were logged for this raid."
L.StrLoggerEmptyBossAttendeesSelectRaid = "Select a raid, then a boss, to inspect that fight's attendees."
L.StrLoggerEmptyBossAttendeesSelectBoss = "Select a boss to inspect that fight's attendees."
L.StrLoggerEmptyBossAttendees = "No attendees were recorded for this boss."
L.StrLoggerEmptyRaidAttendeesSelectRaid = "Select a raid to inspect its roster timeline."
L.StrLoggerEmptyRaidAttendees = "No roster snapshots were recorded for this raid."
L.StrLoggerEmptyBossParticipationSelectRaid = "Select a raid, then a player, to inspect boss participation."
L.StrLoggerEmptyBossParticipationSelectPlayer = "Select a player to inspect boss participation."
L.StrLoggerEmptyBossParticipation = "No boss participation was recorded for this player."
L.StrLoggerEmptyLootSelectRaid = "Select a raid to inspect loot history."
L.StrLoggerEmptyLoot = "No loot was logged for this raid."
L.StrLoggerEmptyLootFiltered = "No loot matches the current boss or player filter."

-- Raids List:
L.StrRaidsList = "Raids List"
L.StrSetCurrent = "Set Current"
L.StrConfirmDeleteRaid = "Are you sure you want to delete this raid log?"
L.StrRaidCurrentTitle = "Duplicate Notice"
L.StrRaidsCurrentHelp =
	"Sometimes you may notice duplicate raid creation. If that happends, make sure to simply set the selected one as current and delete all similar ones above it."
L.ErrCannotDeleteRaid = "Cannot delete the current raid."
L.ErrCannotSetCurrentRaidSize = "Cannot set a raid with a different size as current raid."
L.ErrCannotSetCurrentRaidDifficulty = "Cannot set a raid with a different difficulty as current raid."
L.ErrCannotSetCurrentRaidReset = "Cannot set an expired raid as current raid."
L.ErrCannotSetCurrentNotRaidLeader = "Only the raid leader can set the current raid."
L.ErrCannotSetCurrentNotInRaid = "You must be in a raid group to set the current raid."
L.ErrCannotSetCurrentNotInInstance = "You must be inside a raid instance to set the current raid."
L.ErrCannotSetCurrentZoneMismatch = "Cannot set a raid from a different zone as current raid."
L.LogRaidSetCurrent = "Current raid set to #%d (%s, %d-player)."
L.StrNewRaidSessionChange = "Raid session: zone or size changed; starting a new raid."

L.StrTrashMob = "Trash Mob"

-- Raid Attendees:
L.StrRaidAttendees = "Raid Attendees"
L.StrJoin = "Join"
L.StrLeave = "Leave"
L.StrIlvl = "iLvl"
L.StrSpec = "Spec"
L.StrInspectItems = "Inspect items"
L.BtnForceInspect = "Force"
L.StrInspectQueued = "Queued"
L.StrInspectPending = "Pending"
L.MsgForceInspectMissingUnit = "The selected player is not available in the current raid roster."
L.MsgForceInspectOffline = "The selected player is offline."
L.MsgForceInspectOutOfRange = "The selected player is out of inspect range."
L.MsgForceInspectCannotInspect = "The selected player cannot be inspected right now."
L.MsgForceInspectNotifyFailed = "The inspect request could not be started."
L.StrInspectSkipped = "Skipped"
L.StrInspectSkippedReason = "Skipped: %s"
L.StrInspectTimeout = "Timeout"
L.StrInspectFailed = "Failed"
L.StrInspectFailedReason = "Failed: %s"
L.StrInspectNotInspected = "Not inspected"

-- Raid loot list:
L.StrRaidLoot = "Raid Loot"
L.StrUnknown = "Unknown"
L.StrNone = "None"
L.StrConfirmDeleteItem = "Are you sure you want to delete this item from the log?"
L.StrEditItemLooter = "Change winner"
L.StrEditItemLooterHelp = "Enter the name of the winner:"
L.StrEditItemRollType = "Change roll type"
L.StrEditItemRollValue = "Change roll value"
L.StrEditItemRollValueHelp = "Enter the value of the roll:"
L.StrLoggerSharedSource = "Shared"
L.StrLoggerSharedSourceTooltipSources = "Possible sources:"
L.StrLoggerShareTitle = "Share Raid History"
L.StrLoggerShareRecipient = "Group member"
L.StrLoggerShareSummary = "%s\n%s - %s - %d loot records"
L.StrLoggerShareNoRaid = "Select a raid to share."
L.StrLoggerShareRequiresGroup = "Join a group to share raid history."
L.StrLoggerShareCompletedOnly = "Raid history sharing is available for completed raids only."
L.StrLoggerRaidOfferPrompt = "%s offered this raid history:\n%s"
L.StrLoggerSyncStatus = "Current raid sync: %s"
L.StrLoggerHistoryShareImported = "Raid history from %s was imported."
L.StrLoggerHistoryShareAlreadyPresent = "Raid history from %s was already present."
L.StrLoggerHistoryShareConflict = "Raid history from %s differed; both copies were kept."
L.StrLoggerHistoryShareDeclined = "Raid history sharing with %s was declined."
L.StrLoggerHistoryShareFailed = "Raid history sharing with %s failed."

-- ==================== Logger: EditBox Frame ==================== --
-- Error Messages:
L.ErrLoggerInvalidRaid = "Invalid raid selection for Logger edit."
L.ErrLoggerInvalidItem = "Invalid loot item selection for Logger edit."
L.ErrLoggerWinnerEmpty = "Please enter a valid winner name."
L.ErrLoggerWinnerNotFound = "Winner not found in raid or boss attendees: %s"
L.ErrLoggerInvalidRollValue = "Invalid roll value. Enter a non-negative number."

-- ==================== Logger: Export Frame ==================== --
L.StrLoggerExportTitle = "Logger CSV Export"
L.StrLoggerExportHint = "Select an export type, then press Ctrl+C to copy the CSV data."
L.BtnLoggerExportLootCSV = "Loot CSV"
L.BtnLoggerExportRaidAttendanceCSV = "Raid Attendance CSV"
L.ErrLoggerExportFailed = "Logger export failed: %s"

-- ==================== Slash Commands ==================== --
L.StrCmdCommands = "Commands: valid subcommands for |caaf49141/%s|r:"
L.StrCmdToggle = "shows or hides the main window"
L.StrCmdHelp = "show available commands or details for one command"
L.StrCmdConfig = "shows or hides configuration window"
L.StrCmdConfigReset = "restore default options"
L.StrCmdGrouper = "access LFM Spam related commands"
L.StrCmdAchiev = "look for achievement ID to use for LFM"
L.StrCmdWarnings = "access warnings related commands"
L.StrCmdLogger = "access loot history and raid attendance commands"
L.StrCmdDebug = "toggle debugger or use test helpers: debug on|off|level <name|num>|raid|raidgrid"
L.StrCmdDebugLevel = "show or set the active log level"
L.StrCmdDebugRaid = "use synthetic raid and roll test helpers"
L.StrCmdDebugRaidSeed = "add or reactivate 4 synthetic players in the current raid"
L.StrCmdDebugRaidClear = "remove synthetic players from the current raid when safe"
L.StrCmdDebugRaidRolls = "make the 4 synthetic players roll on the active item (optional: tie)"
L.StrCmdDebugRaidRoll = "make one synthetic player roll: roll <1-4|name> [1-100]"
L.StrCmdDebugRaidGrid = "show and configure the Raid Grid Debug player count"
L.StrCmdCounter = "shows or hides loot counter window"
L.StrCmdQuickBar = "show or hide QuickBar"
L.StrCmdQuickBarShow = "show QuickBar"
L.StrCmdQuickBarHide = "hide QuickBar"
L.StrCmdLFMStart = "starts LFM spam"
L.StrCmdLFMStop = "stops LFM spam"
L.StrCmdReserves = "access Loot Reserve commands"
L.StrCmdReservesImport = "import reserves from SoftRes CSV data"
L.StrCmdReservesCheck = "print a local SoftRes readiness report"
L.StrCmdReservesAlias = "map an imported SoftRes name to the current raid name"
L.StrCmdReservesUnalias = "remove a SoftRes name alias"
L.StrCmdReservesAliases = "list configured SoftRes name aliases"
L.StrCmdReservesSync = "request SoftRes data metadata from grouped RMA clients"
L.StrCmdReservesMeta = "show local SoftRes data metadata"
L.StrCmdReservesClearCache = "clear synced runtime SoftRes data cache"
L.StrCmdSpecInspect = "refresh cached spec icons; use force to refresh all inspectable raid members"
L.StrCmdValidate = "run data validation commands"
L.StrCmdValidateRaids = "validate raid history schema and invariants"
L.StrCmdMinimapPos = "set minimap button angle"
L.StrCmdPerf = "toggle performance logging: perf on|off|threshold <ms>|report|audit|items|reset"
L.StrCmdPerfOn = "enable runtime performance logging"
L.StrCmdPerfOff = "disable runtime performance logging"
L.StrCmdPerfThreshold = "set the slow-block logging threshold in milliseconds"
L.StrCmdPerfReport = "show runtime performance aggregate stats"
L.StrCmdPerfAudit = "show combined operational performance summary"
L.StrCmdPerfItems = "show item info and tooltip request metrics"
L.StrCmdPerfReset = "clear runtime performance aggregate stats"
L.StrCmdVersion = "show local addon version and compatibility details"
L.StrCmdBug = "print a local diagnostic summary for bug reports"

L.StrUnknown = "unknown"
L.StrYes = "yes"
L.StrNo = "no"
L.StrEnabled = "enabled"
L.StrDisabled = "disabled"
L.MsgDebugOn = "Debug: enabled."
L.MsgDebugOff = "Debug: disabled."
L.MsgDebugRaidGridShown = "Raid Grid Debug shown with %d fake players."
L.MsgDebugRaidGridInvalidCount = "Use: /rma debug raidgrid [1-40]"
L.MsgPerfOn = "Performance logging: enabled (threshold=%sms)."
L.MsgPerfOff = "Performance logging: disabled."
L.MsgPerfStatus = "Performance logging: %s (threshold=%sms)."
L.MsgPerfThreshold = "Performance logging threshold: %sms."
L.MsgPerfThresholdInvalid = "Performance logging threshold must be a non-negative number of milliseconds."
L.MsgPerfReportEmpty = "Performance report: no measured blocks."
L.MsgPerfReportTitle = "Performance report: %d block(s)."
L.MsgPerfReportRow = "%2d) %s count=%d total=%sms avg=%sms max=%sms"
L.MsgPerfAuditRuntime = "Performance audit: runtime blocks=%d total=%sms top=%s total=%sms max=%sms."
L.MsgPerfAuditItems = "Performance audit items: requests=%d joined=%d pending=%d GetItemInfo=%d tooltip=%d."
L.MsgPerfItemReport =
	"Item performance report: requests=%d started=%d joined=%d immediate=%d pending=%d callbacks=%d completed=%d timeouts=%d cancelled=%d GetItemInfo=%d tooltip=%d."
L.MsgPerfReportReset = "Performance report reset."
L.MsgDebugRaidNoCurrent = "Debug raid: no current raid available."
L.MsgDebugRaidSeeded = "Debug raid: synthetic players=%d added=%d refreshed=%d."
L.MsgDebugRaidCleared = "Debug raid: synthetic players removed=%d kept=%d."
L.MsgDebugRaidClearResetRolls = "Debug raid: current roll state was reset during cleanup."
L.MsgDebugRaidNoActiveRoll = "Debug raid: no active roll session is accepting rolls."
L.MsgDebugRaidUnknownPlayer = "Debug raid: unknown synthetic player '%s'. Use 1-4 or a debug name."
L.MsgDebugRaidInvalidRoll = "Debug raid: roll value must be between 1 and 100."
L.MsgDebugRaidRollSingle = "Debug raid: %s rolled %d."
L.MsgDebugRaidRolls = "Debug raid: submitted %d/%d synthetic rolls."
L.MsgDebugRaidRollsTie = "Debug raid: submitted %d/%d synthetic rolls with tie=%d at roll=%d."
L.MsgDebugRaidRollsPartial = "Debug raid: submitted %d/%d synthetic rolls; first rejection=%s."
L.MsgDebugRaidRollRejected = "Debug raid: %s roll rejected (%s)."
L.MsgTimerStatsReset = "Timer stats reset."
L.MsgTimerModuleUnavailable = "Timer module not available."
L.MsgTimerStatsSummary = "Timers: active=%d (max=%d) created=%d cancelled=%d completed=%d"
L.MsgTimerStatsRow = "%2d) [%s] %s | age:%.1fs dur:%.2fs"
L.MsgTimerStatsTip = "Tip: /rma debug timers reset  |  sort: age|dur|target"
L.MsgSpammerAutoStopDuration = "LFM spam auto-stopped after %d sec (safety cap)."
L.MsgSpammerAutoStopMessages = "LFM spam auto-stopped after %d messages (safety cap)."
L.ErrSpammerRuntime = "LFM spam stopped: %s."
L.WarnSpammerCallbackFailed = "LFM spam callback failed: %s."
L.MsgMinimapPosSet = "Minimap: angle set to %s."
L.MsgDefaultsRestored = "Options: defaults restored."
L.MsgConfigPresetApplied = "Options: preset applied."
L.MsgLoggerMaintenanceUnavailable = "Loot History maintenance is unavailable."
L.MsgLoggerHistoryScanned = "Loot History: scanned %d raid log(s), empty=%d, missing sources=%d, invalid sources=%d."
L.MsgLoggerHistoryPurged = "Loot History: purged %d raid log(s)."
L.MsgLoggerLootSourcesRebuilt =
	"Loot History: rebuilt sources for %d loot item(s), created %d source record(s), unresolved %d."
L.MsgLoggerCleanupDone = "Loot History: cleanup removed %d raid log(s) and %d loot item(s)."
L.MsgLoggerMaintenancePartial = "Loot History: maintenance stopped after committing partial changes; %d raid log(s) and %d item(s) were updated."
L.MsgLoggerCleanupNoSelection = "Loot History: cleanup cancelled because no delete option was selected."
L.MsgRaidWarningsCleared = "Raid Warning: cleared %d saved message(s)."
L.MsgLogLevelCurrent = "Log level: current=%s."
L.MsgLogLevelSet = "Log level: set=%s."
L.MsgLogLevelUnknown = "Unknown log level: %s."
L.MsgLogLevelList = "Log levels: error, warn, info, debug, trace, spam (or 1-6)."
L.MsgVersionTitle = "RMA version:"
L.MsgVersionAddon = "Addon: %s"
L.MsgVersionInterface = "Interface: %s"
L.MsgVersionRaidSchema = "Raid schema: %s"
L.MsgVersionSyncProtocol = "Sync protocol: %s"
L.MsgVersionCheckSent = "Version check: request sent to group."
L.MsgVersionCheckNotInGroup = "Version check: you must be in a group."
L.MsgVersionCheckPeer = "Version: %s addon=%s interface=%s schema=%s sync=%s"
L.MsgBugReportTitle = "RMA bug report:"
L.MsgBugReportLog = "Log: level=%s debug=%s"
L.MsgBugReportCurrentRaid = "Current raid: index=%s nid=%s"
L.MsgBugReportRaidHistory = "Raid history: %d"
L.MsgBugReportReserves = "Reserves: players=%d entries=%d"
L.MsgBugReportRole = "Role: inRaid=%s leader=%s assistant=%s masterLooter=%s"
L.MsgReserveItemsRequested = "Reserves: requested info for %s missing items."
L.MsgReserveItemsReady = "Reserves: all item infos are available."
L.MsgReserveItemsQueryCooldown = "Reserves: query cooldown active (%d sec)."
L.MsgReservesImportRows = "Reserves import rows: valid=%d skipped=%d."
L.MsgReservesSyncRequested = "Reserves sync: metadata request sent."
L.MsgReservesSyncDataRequested = "Reserves sync: data request sent."
L.MsgReservesSyncNotInGroup = "Reserves sync: you must be in a group."
L.MsgReservesSyncMeta = "Reserves sync: %s checksum=%s mode=%s players=%d entries=%d."
L.MsgReservesSyncMetaLocal = "Reserves sync local: source=%s checksum=%s mode=%s players=%d entries=%d runtime=%s."
L.MsgReservesSyncApplied = "Reserves sync: runtime cache updated from %s."
L.MsgReservesSyncFailed = "Reserves sync failed: %s."
L.MsgReservesSyncCacheCleared = "Reserves sync: runtime cache cleared."
L.MsgReservesSyncNoRuntimeCache = "Reserves sync: no runtime cache is active."
L.MsgSoftResReadinessTitle = "SoftRes readiness:"
L.MsgSoftResReadinessCurrentItem = "Current item: %s"
L.MsgSoftResReadinessItemSummary = "Current item SoftRes: %d/%d players in raid."
L.MsgSoftResReadinessItemPresent = "Item in raid: %s"
L.MsgSoftResReadinessItemMissing = "Item outside raid: %s"
L.MsgSoftResReadinessItemNone = "Current item SoftRes: no reserves."
L.MsgSoftResReadinessNoData = "SoftRes readiness: no imported SoftRes data."
L.MsgSoftResReadinessRosterSummary = "Imported SoftRes: %d players, %d in raid, %d outside raid."
L.MsgSoftResReadinessRosterPresent = "In raid: %s"
L.MsgSoftResReadinessRosterMissing = "Outside raid: %s"
L.MsgSoftResReadinessHealth = "Health: %s"
L.StrSoftResReadinessHealthOk = "OK"
L.StrSoftResReadinessHealthWarning = "Warning"
L.StrSoftResReadinessHealthError = "Error"
L.StrSoftResReadinessNameMatch = "%s -> %s"
L.MsgSoftResReadinessIssues = "Issues: %d"
L.MsgSoftResReadinessHealthImportedOutside = "Imported names outside raid: %d"
L.MsgSoftResReadinessHealthRaidWithout = "Raid players without exact SoftRes: %d"
L.MsgSoftResReadinessHealthNameMatches = "Suggested name matches: %d"
L.MsgSoftResReadinessHealthItemNoReserves = "Issue: current item has no SoftRes entries."
L.MsgSoftResReadinessHealthItemNoEligible = "Issue: current item has SoftRes entries, but none are in raid."
L.MsgSoftResReadinessNameMatches = "Possible name matches: %s"
L.MsgSoftResReadinessAliases = "Applied aliases: %s"
L.MsgSoftResReadinessUnmatchedReserve = "Unmatched SoftRes names: %s"
L.MsgSoftResReadinessUnmatchedRaid = "Raid players without exact SoftRes: %s"
L.WhisperSoftResHeader = "Your SoftRes reserves:"
L.WhisperSoftResEntry = "%d. %s"
L.WhisperSoftResNone = "No reserves found for %s."
L.WhisperSoftResAdded = "Your %s reserve is added!"
L.WhisperSoftResInvalidItem = "Shift-click an item link after +sr to add a reserve."
L.WhisperSoftResAdmissionLimited = "Too many SoftRes requests. Please wait a few seconds and try again."
L.WhisperSoftResCapacity = "SoftRes signup is full. Ask the raid leader for help."
L.ChatSoftResWhisperHelpQuery = "SoftRes: To see your reserves /w %s +sr"
L.ChatSoftResWhisperHelpAdd = "SoftRes: To add one and receive confirmation /w %s +sr [item link]"
L.MsgFeatureUnavailable = "Feature '%s' action '%s' is not available."
L.MsgLoggerRaidOfferSent = "Raid #%s offered to %s."
L.MsgLoggerRaidOfferTargetUnavailable = "Select a current group member."
L.MsgLoggerRaidOfferUnavailable = "That raid offer is no longer available."
L.MsgRaidHistoryQuarantined = "Raid history is quarantined (%s: %s). Back up SavedVariables, restore a compatible RMA_Raids value or remove only RMA_Raids, then /reload."
L.StrRaidArchiveInvalidType = "invalid SavedVariable type"
L.StrRaidArchiveUnsupportedFormat = "unsupported archive format"
L.StrRaidArchiveCorrupt = "corrupt archive structure"
L.StrRaidHistoryQuarantined = "Raid history unavailable (quarantined)."
L.RaidSyncStatusQuarantined = "Raid history synchronization suspended: RMA_Raids is quarantined."
L.RaidSyncStatusUpToDate = "Raid data synchronized."
L.RaidSyncStatusRecovering = "Recovering missing raid data."
L.RaidSyncStatusHandover = "Changing Master Looter."
L.RaidSyncStatusTransferringHistory = "Transferring historical raid."
L.RaidSyncStatusSuspended = "Raid synchronization suspended because peer data conflicts."
L.RaidSyncStatusFailed = "Raid synchronization failed."
L.StrCmdLoggerShare = "Offer the selected completed raid to a current group member."
L.MsgValidateUnavailable = "Validation service is not available."
L.MsgSpecInspectNoService = "Spec inspect service is unavailable."
L.MsgSpecInspectRefresh = "Spec inspect refresh: queued=%d cached=%d skipped=%d."
L.MsgValidateRaidsNoData = "Raid validation: no raids available."
L.MsgValidateRaidsSummary = "Raid validation: raids=%d ok=%d warn=%d err=%d schema=%d."
L.MsgValidateRaidsDetailsTruncated = "Raid validation: %d detail rows were truncated."
L.MsgValidateDetailRaidNotTable = "raid[%d] nid=%s: record is not a table."
L.MsgValidateDetailNormalizeFailed = "raid[%d] nid=%s: normalization failed."
L.MsgValidateDetailSchemaMissing = "raid[%d] nid=%s: schemaVersion is missing."
L.MsgValidateDetailSchemaNewer = "raid[%d] nid=%s: schemaVersion=%d is newer than current=%d."
L.MsgValidateDetailCounterTooLow = "raid[%d] nid=%s: %s=%d is lower than required=%d."
L.MsgValidateDetailPlayerCountType = "raid[%d] nid=%s: players[%d].count is not a number."
L.MsgValidateDetailPlayerCountNegative = "raid[%d] nid=%s: players[%d].count is negative (%d)."
L.MsgValidateDetailLootMissingBoss = "raid[%d] nid=%s: loot[%d].bossNid=%d does not exist."
L.MsgValidateDetailLootNoBossTrash = "raid[%d] nid=%s: loot[%d] has no bossNid and no _TrashMob_."
L.MsgValidateDetailBossAttendeeInvalid = "raid[%d] nid=%s: bossKills[%d].players[%d] is not a valid playerNid."
L.MsgValidateDetailBossAttendeeMissingPlayer =
	"raid[%d] nid=%s: bossKills[%d].players[%d]=%d does not match any raid player."
L.MsgValidateDetailLootMissingLooter = "raid[%d] nid=%s: loot[%d] has no looterNid."
L.MsgValidateDetailLootMissingLooterNid = "raid[%d] nid=%s: loot[%d].looterNid=%d does not exist."
L.MsgValidateDetailRuntimeOutside = "raid[%d] nid=%s: private key is not allowed in persisted raid data: %s."
L.MsgValidateDetailUnknown = "raid[%d] nid=%s: %s."

-- ==================== Raid & Loot Locales ==================== --
L.RaidZones = {
	-- The Burning Crusade
	["Karazhan"] = "Karazhan",
	["Gruul's Lair"] = "Gruul's Lair",
	["Magtheridon's Lair"] = "Magtheridon's Lair",
	["Serpentshrine Cavern"] = "Serpentshrine Cavern",
	["The Eye"] = "The Eye", -- Tempest Keep: The Eye
	["Battle for Mount Hyjal"] = "Battle for Mount Hyjal",
	["Black Temple"] = "Black Temple",
	["Sunwell Plateau"] = "Sunwell Plateau",
	["Zul'Aman"] = "Zul'Aman",

	-- Wrath of the Lich King
	["Naxxramas"] = "Naxxramas",
	["The Obsidian Sanctum"] = "The Obsidian Sanctum",
	["The Eye of Eternity"] = "The Eye of Eternity",
	["Vault of Archavon"] = "Vault of Archavon",
	["Ulduar"] = "Ulduar",
	["Onyxia's Lair"] = "Onyxia's Lair", -- Note: Onyxia is also present in Classic
	["Trial of the Crusader"] = "Trial of the Crusader",
	["Trial of the Grand Crusader"] = "Trial of the Grand Crusader", -- Already present, keeping it
	["Icecrown Citadel"] = "Icecrown Citadel",
	["The Ruby Sanctum"] = "The Ruby Sanctum", -- Already present, keeping it
}
-- The reason we are using these is because of the missing
-- UNIT_DIED event once these bosses are dealt with.
L.BossYells = {
	-- Naxxramas
	["I grow tired of these games. Proceed, and I will banish your souls to oblivion!"] = "Four Horsemen",
	-- Ulduar
	["You rush headlong into the maw of madness!"] = "Iron Council", -- Normalmode - Stormcaller Brundir last
	["What have you gained from my defeat? You are no less doomed, mortals!"] = "Iron Council", -- Semi-Hardmode - Runemaster Molgeim last
	-- ["Impossible..."] = MRT_IsInstanceUlduar("Iron Council"),  -- Hardmode - Steelbreaker last  // also yelled by Lich King -> instance check necessary
	["I... I am released from his grasp... at last."] = "Hodir",
	["Stay your arms! I yield!"] = "Thorim",
	["His hold on me dissipates. I can see clearly once more. Thank you, heroes."] = "Freya",
	["It would appear that I've made a slight miscalculation. I allowed my mind to be corrupted by the fiend in the prison, overriding my primary directive. All systems seem to be functional now. Clear."] = "Mimiron",
	["I've rearranged the reply code. Your planet will be spared. I cannot be certain of my own calculations anymore."] = "Algalon",
	-- Trial of the Crusader
	["A shallow and tragic victory. We are weaker as a whole from the losses suffered today. Who but the Lich King could benefit from such foolishness? Great warriors have lost their lives. And for what? The true threat looms ahead - the Lich King awaits us all in death."] = "Faction Champions",
	["The Scourge cannot be stopped..."] = "Val'kyr Twins",
	-- Icecrown Citadel
	["Don't say I didn't warn ya, scoundrels! Onward, brothers and sisters!"] = "Gunship Battle", -- Muradin
	["The Alliance falter. Onward to the Lich King!"] = "Gunship Battle", -- Saurfang
	["My queen, they... come."] = "Blood Prince Council", -- Prince Keleseth
	["I AM RENEWED! Ysera grant me the favor to lay these foul creatures to rest!"] = "Valithria Dreamwalker", -- Dreamwalker
	-- Ruby Sanctum
	["Relish this victory, mortals, for it will be your last. This world will burn with the master's return!"] = "Halion", -- Halion
}
